### ISSUE TITLE
urlParams does not decode "+" character in query params

### ISSUE THREAD

**Issue by bantic** [jquery/qunit#1000]
The [`getUrlParams` function](https://github.com/jquery/qunit/blob/f13038f8530da11a4c3793f35ffe4d4e1d0531a2/reporter/urlparams.js#L69) does not decode the plus character (`+`) in query parameters, which can cause QUnit to fail to match modules or test names when the `module` or `filter` query parameters include spaces encoded as plus characters.

For example, if a test named "my test" exists, and the tests page is at "http://localhost:4200/tests", then the URL "http://localhost:4200/tests?filter=my+test" will fail to run the test because it does not decode the parameter "my+test" to "my test".

The test- and module-filtering still works in most cases because QUnit's [url-generating function `setUrl`](https://github.com/jquery/qunit/blob/347a8381c803a2122279e93af51892c4351f841d/reporter/html.js#L211) encodes spaces in the query parameters as `%20`, and `getUrlParams` *does* decode `%20` as a space.

We have a use case where a uri-normalization library is running on the test page and it replaces the `%20` with `+` in the url's query parameters before QUnit runs `getUrlParams`.

According to the W3, spaces in query parameter names and values (mime type application/x-www-form-urlencoded) [should be replaced with `+`, not `%20`](https://www.w3.org/TR/REC-html40/interact/forms.html#h-17.13.4.1), so it seems like the correct behavior would be:
  * for QUnit's HTML Reporter UI to use plus characters instead of spaces when generating query params
  * for QUnit's `getUrlParams` to decode plus characters as spaces

**Comment by rwjblue** [comment]
@trentmwillis - FWIW, this is the result of the bug/issue that I pestered you about in slack a week or two ago.  Many thanks to @bantic for tracking down what is going on (and his continued efforts to fix many encoding/decoding related issues in Ember's route-recognizer).

**Comment by trentmwillis** [comment]
@rwjblue, I thought this might be related to that. Seems like a reasonable ask to support `%20` and `+` as space-encodings for params since URIs should support them anyway.

**Comment by gibson042** [comment]
I don't think we need to go to the trouble of complicating `setUrl`, but I approve of more liberal decoding.

**Comment by bantic** [comment]
neat — this is issue number 1000 and it was closed by commit number 1000. :)

**Comment by leobalter** [comment]
https://twitter.com/qunitjs/status/732620820049235968
