### ISSUE TITLE
Skipped tests runtime should be undefined

### ISSUE THREAD

**Issue by flore77** [jquery/qunit#1004]
## Problem
While working on the [js-reporter](https://github.com/js-reporters/js-reporters) project I have discovered that also the `runtime` of `skipped tests` is a `Number`. 

We on the `js-reporters` think that the `runtime` should be `undefined`, because the test does not run, it is skipped, so it cannot have a runtime.

I looked over the docs about the `runtime` prop on the `testDone` callback, where it is described:

> The total runtime in millseconds of the test, including beforeEach and afterEach

But, also all `hooks` for a skipped test, are also [skipped](https://github.com/jquery/qunit/blob/44662651017be2fedd550685227d6916767ba16b/src/test.js#L188-L190).

## Solution

To achieve this, we should only [modify the runtime](https://github.com/jquery/qunit/blob/44662651017be2fedd550685227d6916767ba16b/src/test.js#L231) of the object that is passed as param to the callback on `testDone`, something like:

```js
runLoggingCallbacks( "testDone", {
  ...
  runtime: (!!this.skip) ? undefined : this.runtime,
  ... 
} );
```

I have done this change locally and all tests are passing. I want also to write some tests to check the tests runtime for a `good coverage`. Here is a [gist](https://gist.github.com/flore77/106860feffdeaa24c8bad12705430943) about how I think to test it, but I don't know how to simulate a test that is failing, so that  I can get its runtime.

**Comment by leobalter** [comment]
I'm not sure how the type is a concern, as the expected value for skipped tests is 0 or close (I hope) and replacing it with undefined would be a breaking change.

Rather than reading the runtime, js-reporters should ignore the value on skipped tests, as it is irrelevant as an undefined.

**Comment by trentmwillis** [comment]
I agree with @leobalter the value shouldn't matter too much.

@flore77 could you link to an explanation (or explain yourself), why using `undefined` is preferable over an actual number? In my mind, it makes sense to report a number (even `0`), for more accuracy in understanding what the test suite is doing.

**Comment by jzaefferer** [comment]
How about making sure that runtime is always 0 for skipped tests? That should work for js-reporters as well.

**Comment by leobalter** [comment]
> How about making sure that runtime is always 0 for skipped tests? That should work for js-reporters as well.

Works for me. 👍

**Comment by jzaefferer** [comment]
And I guess if we set it to 0, we don't really need to add tests for that...

**Comment by flore77** [comment]
@trentmwillis sure. For me it does not make sense, because for a test to have a `runtime`, it should get the chance to `execute`, to run some instructions, but skipped tests are simply skipped, neither the hooks are executed for them. For example Mocha's emitted objects for skipped tests do not have the runtime (actually it is called duration for Mocha)  property at all.

> Rather than reading the runtime, js-reporters should ignore the value on skipped tests

@leobalter, sure js-reporters can easily ignore the value, we are currently doing this in [Fix qunit adapter #58](https://github.com/js-reporters/js-reporters/pull/58).

Anyway, to ensure the runtime is 0, sounds fair :smiley:

**Comment by jzaefferer** [comment]
>  For example Mocha's emitted objects for skipped tests do not have the runtime (actually it is called duration for Mocha) property at all.

@leobalter @trentmwillis considering that the property is indeed undefined for skipped Mocha tests, would you consider adopting that for QUnit as well?

**Comment by trentmwillis** [comment]
It seems reasonable to me, though we would need to make sure it gets in the 2.0 release or else we'll have to wait for 3.0. I'm also okay with defaulting it to `0`.

**Comment by leobalter** [comment]
I still prefer casting it to 0, as skipped tests will be consistent with other test calls and test extensions (e.g. `.todo`)

undefined seems reasonable if not providing the `runtime` key at all, so that would be an undefined reference, not the value.
