### ISSUE TITLE
QUnit fails in IE 6, 7 and 8.

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [jquery/qunit#1012]
qunitjs.com documents that the browser support is:

> IE6+ and Current - 1 for Chrome, Firefox, Safari and Opera.

So I am assuming that IE 6, 7 and 8 are supported.

--

What happens is that once upgrading to QUnit 2.0.0 my tests for IE 6, 7 and 8 started failing in Sauce Labs:

* Failing PR: https://github.com/js-cookie/js-cookie/pull/216
* Failing Build: https://travis-ci.org/js-cookie/js-cookie/builds/138708313#L1035-L1056
* This is the code that exposes the test info for Sauce Labs: https://github.com/js-cookie/js-cookie/blob/cfa66f314a3d380083cf50ffe733234b6db7b331/test/utils.js#L7-L24

It will be pretty hard to track down the root cause of this issue, so I was wondering if anyone could shed some light on something obvious that might have changed between v1 and v2 that could have been breaking the unit tests in those browsers?

The code being tested is working, because it only fails once QUnit is upgraded and only in those specific IE browsers.

Any ideas?

**Comment by trentmwillis** [comment]
I believe that documentation is out of date. My understanding is that our 2.0 release was intended to support [the same browsers as jQuery does](https://jquery.com/browser-support/) which is IE 9+.

cc @leobalter to confirm that is our browser policy now (I'll open a PR to fix if so).

**Comment by leobalter** [comment]
I sleeped on that part. Trent is right, the support for QUnit 2+ is the
equivalent for minimal support on jQuery 3 and the current major version of
Ember.

That means IE9+ only.

I'm sorry for the miscommunication.

**Comment by FagnerMartinsBrack** [comment]
Thanks @leobalter 👍
