### ISSUE TITLE
HTMLReporter: apply/reset buttons, in module dropdown, disappear when they shouldn't be

### ISSUE THREAD

**Issue by Arkni** [jquery/qunit#1013]
**QUnit version:** 2.0.0

**Steps to reproduce:**

Let's say I have 3 modules: `rules`, `messages` and `aria`.
* Select the module `rules` from the dropdown: the buttons apply/reset will appear (_expected_)
* Select another module (`messages` for example): the buttons still appear (_expected_)
* Uncheck the module `rules`: the buttons will disappear (_unexpected_)

Instead they should appear because the dropdown is still dirty and I didn't commit my choices yet.

See attached screen cast:
![qunit-anim](https://cloud.githubusercontent.com/assets/6888059/16359909/bd3137a8-3b36-11e6-832d-cdb4078d7353.gif)

**Comment by trentmwillis** [comment]
Thanks for the report, I believe this is an issue with [the dirty checking done here](https://github.com/jquery/qunit/blob/master/reporter/html.js#L433), but don't have much time to dig in further.

@Arkni if you have time to investigate further and open a PR, it would be much appreciated!

**Comment by shivamdixit** [comment]
@trentmwillis I'll pick this one. Can you assign it to me?

**Comment by Arkni** [comment]
> I believe this is an issue with the dirty checking done here,

That what I came across too when trying to dig into the source code.

> @Arkni if you have time to investigate further and open a PR

It looks like @shivamdixit already started digging into it and writing a fix.

**Comment by shivamdixit** [comment]
@Arkni PR shared :)

**Comment by Arkni** [comment]
Thanks @shivamdixit
