### ISSUE TITLE
Assert: "throws" removed signature (block, string, string) not in migration guide despite reference to migration guide in exception message

### ISSUE THREAD

**Issue by platinumazure** [jquery/qunit#1015]
Maybe this belongs on jquery/qunitjs.com, if so I can move it there.

The "throws" assertion throws an exception when given (block, string, string) arguments. It mentions the migration guide, but the migration guide does not contain information about this at all.

**Comment by leobalter** [comment]
Yes, this is missing in the guide and we need to add this to qunitjs.com. Do you mind opening an issue there? We may close this one when everything is set.

**Comment by platinumazure** [comment]
@leobalter Thanks for the quick response. Do you believe there is anything to do in this repo? (I'm leaning towards no.)

**Comment by leobalter** [comment]
AFAIK, that was a change we predicted for 2.0, but as a signature change it is not much visible and I missed it.

**Comment by platinumazure** [comment]
@leobalter Fair enough. I'm going to close this since I created the qunitjs.com issue-- please reopen if you believe a code change needs to be done here.
