### ISSUE TITLE
before + beforeEach = hang of test

### ISSUE THREAD

**Issue by vogdb** [jquery/qunit#1016]
```js
QUnit.module('Sample tests', {
  before: function() {
    return new Promise(function(resolve) {
      setTimeout(function() {
        console.log('`before` complete');
        resolve()
      }, 200);
    });
  },
  beforeEach: function() {
    return new Promise(function(resolve) {
      setTimeout(function() {
        console.log('`beforeEach` complete');
        resolve();
      }, 100);
    });
  }
});

QUnit.test('Sample test', function(assert) {
  console.log('Test started!');
  assert.ok(true);
});
```

`'Test started!'` never appears to console. Qunit version is 0.2.0. Resolving through `assert.async()` and `done` produces the same problem.

**Comment by vogdb** [comment]
Does not happen on 1.23.1

**Comment by trentmwillis** [comment]
@vogdb thanks for reporting, will look into it as I believe it has to do with some changes I made to handling async

**Comment by vogdb** [comment]
Additional note. It worked on 1.23.1 cause `before` never was executed. It seems that there are no such hook as `before`.
