### ISSUE TITLE
Does QUnit want to use ESLint?

### ISSUE THREAD

**Issue by platinumazure** [jquery/qunit#1021]
With ESLint and JSCS having joined forces and jQuery core starting to use ESLint, I'm wondering if this is something QUnit is also interested in doing. Was anyone planning to look into it?

Also, if ESLint is consumed here, I have an ESLint plugin [eslint-plugin-qunit](https://github.com/platinumazure/eslint-plugin-qunit) which might be useful to you folks.

I'm happy to do a good amount of the grunt work to set things up if folks are interested in one or both of these propositions. Let me know.

**Comment by jzaefferer** [comment]
I suppose https://github.com/jquery/eslint-config-jquery would be a good starting point.

**Comment by platinumazure** [comment]
Excellent, that's where I was thinking of starting. May I take this as an
endorsement towards switching to ESLint?

**Comment by jzaefferer** [comment]
Seems fine to me, but you should probably wait for confirmation from one of the more active team members.

**Comment by leobalter** [comment]
Regardless of my personal preference, JSCS is not maintained anymore, so it's reasonable to move to ESLint. 

Let's do it.

**Comment by platinumazure** [comment]
@leobalter If you want to wait for ESLint to get to 100% compatibility with JSCS, it certainly makes sense to do that.

**Comment by leobalter** [comment]
It is good to have everything consistent with jQuery's code style and the tools used across the other projects.

Just a quick note: https://github.com/jquery/jquery/commit/02c5e2908c2d99f191f5ec9e365ef2a3d357d1eb

We should review our support list for NodeJS versions (we should keep a compatibility list that supports jQuery 3+) and maybe we might get stuck upgrading ESLint.

**Comment by trentmwillis** [comment]
Overall I am in favor of this.

**Comment by platinumazure** [comment]
@leobalter Any idea why jQuery is sticking to ESLint@2.x? Is it because of the Node 4+ support, or something else?

**Comment by mgol** [comment]
@platinumazure That was the reason but we've since switched to ESLint 3, we just skip linting in Node<4: https://github.com/jquery/jquery/blob/edf7a43/Gruntfile.js#L199-L200

Note that jQuery Core will most likely stop supporting building on Node.js 0.10 in October 2016 and on Node 0.12 in January 2017, i.e. when the upstream support ends for those versions (we've already stopped running the build on Node 5 for the same reason).

**Comment by leobalter** [comment]
Linting can be done in a single Node version, I'm +1 with that.

Testing still need to target Node versions based on major tools using QUnit, dropping support will require a new major version. jQuery Core has plans to stop supporting old Node versions, but QUnit will need to confirm the same will be true with other projects as lodash, Backbone, Ember, etc.

~~un~~fortunately, the test suite should be the last resort supporting legacy.

**Comment by mgol** [comment]
> jQuery Core has plans to stop supporting old Node versions

To be precise, that's only about dropping support for building jQuery in older Nodes, it has nothing to do with jQuery working with them which is both independent on the builder working AND not tested by us for a loooong time - our limited Node tests are run with jsdom which dropped support for Node 0.10 & 0.12 long ago.

That's why it's not such a big deal for us; QUnit has to think about Node more carefully.

**Comment by platinumazure** [comment]
My current status on this:

* I'd like to wait for the ES6/Babel work going on right now. That way I can choose to implement useful ES6 ESLint rules from the beginning, rather than implementing ES5-only rules now and then doing another pass with ES6 rules later.
* This also dovetails with the fact that we seem to be a bit uncertain about dropping support (of any kind) from Node versions less than 4. So it wouldn't be a good idea to use ESLint (at least 3.x) until that is resolved.

**Comment by platinumazure** [comment]
I've submitted a WIP PR on this. I will incorporate feedback and make changes next week, when I have full Internet again.

**Comment by platinumazure** [comment]
In case anyone is following this but not the PR: Got Travis config working (linting is only done on latest Node), so hopefully we can finish this up soon.
