### ISSUE TITLE
QUnit 2.0 IE8 support

### ISSUE THREAD

**Issue by gkatsev** [jquery/qunit#1031]
Hey, I tried looking but didn't find a good definite answer about this. Does QUnit 2.0 drop IE8 support? We just tried updating to it on videojs and then noticed that the tests were failing.
It turned out the issue was an `Object.defineProperty` call that doesn't work on IE8.
Thanks.

**Comment by trentmwillis** [comment]
There's a note about browser compatibility on [qunitjs.com](http://qunitjs.com/):

> QUnit currently supports [the same browsers as jQuery 3.x](https://jquery.com/browser-support/).

> For legacy browser support, including Internet Explorer versions lower than IE9, please use the 1.x series of QUnit.

**Comment by gkatsev** [comment]
Oh, thanks. I was looking for something like that; I guess I totally missed it.
