### ISSUE TITLE
Is there a good reason why logical expressions might be used in an assertion argument?

### ISSUE THREAD

**Issue by platinumazure** [jquery/qunit#1032]
Note: This is more a question about usage patterns and best practices, rather than a real issue on the repo-- if this should be moved elsewhere, let me know. QUnit's presence in the \#jquerydev channel of freenode hasn't been very strong (or I've logged on at bad times), and I'm not sure where else to go.

The basic question is, is it ever a good practice to have assertions involving semi-complex expressions (like a logical expression)?

Possible examples:

```js
// 1. Unsure if object exists at this point
assert.ok(obj && obj.someProp, "someProp exists and is truthy");

// 1a. Could separate into multiple assertions
assert.ok(obj, "obj exists");
assert.ok(obj.someProp, "someProp exists and is truthy");

// 2. One property or another should exist
assert.ok(obj.someProp || obj.anotherProp, "someProp or anotherProp exists");

// 2a. But this suggests a possible non-deterministic test, not a great unit test
```

Is there any legitimate use case I'm not thinking of?

**Comment by leobalter** [comment]
the assertion function will only receive the result of the given expressions, it can't see the expression itself.

To be honest, case 1a seems like the appropriate testing for me.

The case 2 seems too loose to make an actual case. What is the real value to assert an object as one property or another with a true-like value? One should look for more precise way to assert a valid information you need there. That might involve some API refactoring and that's where a TDD process does a great job.

**Comment by platinumazure** [comment]
@leobalter I'm aware of the expression being evaluated before being passed to the assert function. The question is whether it might be worthwhile to lint against those expressions.

When you say case 1a is appropriate, does that mean you agree that it is better than 1?

And yeah, I agree that case 2 is loose. That's sort of the point I'm trying to make here.

Background on why I am asking: I'm trying to see if [this issue](https://github.com/platinumazure/eslint-plugin-qunit/issues/50) is worth implementing in my ESLint plugin for QUnit practices. At this point, I haven't yet been dissuaded.

**Comment by leobalter** [comment]
> The question is whether it might be worthwhile to lint against those expressions.

Oh, I see. Now I understand this question connects to linting.

I understand some expressions may still be used within the `.ok`, but maybe a ESLint option to advise against Binary Logical Operators inside assertions would be fine.

**Comment by platinumazure** [comment]
Thanks! I'll leave this open just for a day in case anyone else wants to weigh in, then I'll close, if that's okay with you.

**Comment by jzaefferer** [comment]
I don't have anything to add to the discussion, except agreeing with the outcome. But wanted to add that the eslint-plugin-qunit project looks great! Should get that listed on http://qunitjs.com/plugins/

**Comment by platinumazure** [comment]
Thanks @jzaefferer, I believe it's already there!
