### ISSUE TITLE
before/after hooks run only for first test in module

### ISSUE THREAD

**Issue by brendyna** [jquery/qunit#1037]
I'm running into an issue with before/after hooks using QUnit 2.0.1. Here's the sample module setup I'm working with:

```javascript
QUnit.module("Sample module", function(hooks) {
    hooks.before(function(assert) {
        console.log("Before");
    });

    hooks.after(function(assert) {
        console.log("After");
    });

    QUnit.test("Test A", function(assert) {
        assert.expect(0);
        console.log("Test A ran");
    });

    QUnit.test("Test B", function(assert) {
        assert.expect(0);
        console.log("Test B ran");
    });

    QUnit.test("Test C", function(assert) {
        assert.expect(0);
        console.log("Test C ran");
    });
});
```
and the resultant console output I'm seeing is:
```text
Before
Test A ran
After
Test B ran
Test C ran
```
When I expect to see this:
```text
Before
Test A ran
Test B ran
Test C ran
After
```
I'm roughly following the guidance in the last sample ("Hooks stack on nested modules") on this page, but substituting `before/after` for `beforeEach/afterEach` and without a nested module: https://api.qunitjs.com/QUnit.module/. 

When debugging into qunit.js a bit, I noticed when a hook is run and it checks to see if the module test count matches the number of module tests run, that the number of tests registered for the module isn't accurate (it's 1, "Test A", but "Test B" and "Test C" aren't registered).

Thoughts on what could be going wrong? Happy to provide more info about my setup if desired, and thanks in advance for any help!

**Comment by leobalter** [comment]
can you provide more details on your environment?

http://jsbin.com/tufiluzope/edit?js,output

I'm trying to reproduce this bug but I'm getting the expected result

**Comment by brendyna** [comment]
Thanks, @leobalter, for the quick reply! A few more bullets about my setup:

- I'm using QUnit + RequireJS
- There are nested modules (e.g. parent module is "Static content" and child module is "Side bar"); I'd like the hooks applied in the parent context and reused for each child)
- All child tests within a parent module act on a shared global widget bound to the `#qunit-fixture` element which is setup in the `before` hook and torn down in the `after` hook

I'm guessing I'm running into AMD weirdness or global state weirdness, or a combination of the two (which is to say, not a QUnit issue after all, but an issue w/the complexity of my setup).

Any hints you can provide would still be appreciated if my setup sounds like one you have experience with.

**Comment by platinumazure** [comment]
@brendyna Could you create a JSBin (or equivalent) demonstrating the problem with minimal code?

**Comment by platinumazure** [comment]
@brendyna Could you please create a JSBin (or equivalent) which reproduces your issue with minimal code? (Make sure you use RequireJS, to more closely match your setup.) Thanks!

**Comment by brendyna** [comment]
@platinumazure sure, I'll need a bit of time for that. I'm playing around with things and will report back with what I find.

**Comment by brendyna** [comment]
@platinumazure, @leobalter you guys can go ahead and close this. After further playing around, the issues were on my side (before/after are running correctly now that I've solved issues w/global state and RequireJS).

Sorry to waste your time!

**Comment by leobalter** [comment]
It is never a waste of time. I'm glad you figured it out and it would be awesome if you could share it here so we can avoid it next time.

**Comment by brendyna** [comment]
It's a series of embarrassing mistakes, but happy to share in case someone else ends up in this situation.

I'm still not 100% sure what the root issue is, or if there's something QUnit could do, but here are the setups that did/didn't work to help with repro'ing what I'm seeing. My inkling is it's a race condition of standard loading vs. RequireJS loading, but again I'm not sure. I'm using these technologies:

- RequireJS
- QUnit
- JQuery
- TypeScript (as an FYI; shouldn't impact this situation, AFAIK)

**Note:** The test file is for a Summary page I'm UI unit testing, but the test file/name doesn't matter.

**Setup that DOESN'T work**
The most important things about this setup to note:
- QUnit is included via a manual script tag, whereas JQuery is loaded via RequireJS
- I have the QUnit tests wrapped in the `document.ready` JQuery shortcut (so the tests will run once JQuery loads)

Here's the JSBin: http://jsbin.com/haduha/edit?html,js,console

**Setup that DOES work**
The most important things to note about this setup:
- QUnit is now loaded via RequireJS
- I have to explicitly call `QUnit.start()` to run the tests
- This setup works regardless of whether I have the tests wrapped in the JQuery `document.ready` shortcut

Here's the JSBin: http://jsbin.com/purude/edit?html,js,console

**Comment by dshrestha** [comment]
I am having similar issue when running qunit tests via ember. For me, the before and after hooks are behaving like beforeEach and afterEach hooks where they are executed for every test within module. I tried recreating this issue in jsbin but I was unable to do so since the demo jsbin I am working with doesn't user requirejs.
