### ISSUE TITLE
QUnit.start in tests and module hooks?

### ISSUE THREAD

**Issue by platinumazure** [jquery/qunit#1038]
Hi folks. Just want to confirm, is `QUnit.start()` expected to throw not only in tests but also in module hooks? (My understanding is that `config.current` should be valued in those cases as well.)

I know I can test this myself to get an idea of actual behavior, but I'm also trying to confirm what the expected/supported behavior is intended to be. It will help me make a decision on my [eslint-plugin-qunit](https://github.com/platinumazure/eslint-plugin-qunit) with regard to how `QUnit.start()` calls should be linted.

**Comment by trentmwillis** [comment]
I believe it should throw inside the module hooks as well, since that would be considered part of the test context.

**Comment by platinumazure** [comment]
Excellent, that's all I need for my ESLint plugin question. I will assume that `QUnit.start` within a test or a module hook should be linted (and everything else will have to get benefit of doubt). I can verify the behavior on my own later.

Thanks!
