### ISSUE TITLE
Wording for negated assertions is confusing

### ISSUE THREAD

**Issue by kcgolden** [jquery/qunit#340]
Below is sample output from a passing notEqual() test:

-------------------------
key icon is visible when activeKeys is empty
Expected:	
"none"
Result:	
"inline"
Diff:	
"none" "inline" 

------------------------

The way this is written, it implies that "none" was expected when in fact, we are expecting anything except "none".

**Comment by jzaefferer** [comment]
Prepending "NOT" to the expected value seems fine.

**Comment by platinumazure** [comment]
@jzaefferer I've created PR #822 as a possible fix for this issue, but it's incorrectly flagging the PR as CLA: Error (and the travis build seemed to fail on teardown). Any chance you could take a look and let me know if I'm doing anything wrong?
