### ISSUE TITLE
Confusing line breaks in object diff

### ISSUE THREAD

**Issue by rodneyrehm** [jquery/qunit#348]
![confusing line breaks in object diff](http://rodneyrehm.de/t/github-issue-qunit-object-diff.png)

values should start at the same horizontal offset or be shown in sequence. Current visual is confusing, as it looks like the value could be a key or something.

**Comment by AnishChandran** [comment]
http://fiddle.jshell.net/sj6kdj9g/ 
Is this an simple example about confusing line breaks in diff ? since the "gre": "foo" should be aligned with "foo": "bar ?

**Comment by jzaefferer** [comment]
@AnishChandran that fiddle only has "foo"/"bar" as actual/expected - without linebreaks, there's nothing confusing there.
