### ISSUE TITLE
Latest qunit with phantomjs swallows exceptions from other scripts

### ISSUE THREAD

**Issue by ashwinr** [jquery/qunit#403]
When running qunit (1.11.0) under phantomjs (1.8.1), exceptions in scripts that are not qunit test files are swallowed. They do not show up in phantomjs' console output.

**Comment by jzaefferer** [comment]
Phantomjs 2.0 is still not ready. PhantomJS 1.x is still bad. Whatever.

**Comment by JamesMGreene** [comment]
> Phantomjs 2.0 is still not ready.

Huh?

**Comment by jzaefferer** [comment]
See https://github.com/Medium/phantomjs/issues/288 which lead me eventually to https://github.com/ariya/phantomjs/issues/12948
