### ISSUE TITLE
[QUnit.only] Add support for source-based test filtering (aka exclusive tests)

### ISSUE THREAD

**Issue by ftokarev** [jquery/qunit#496]
I think it would be handy to be able to filter tests right in the source code. This feature is essential when [Karma](http://karma-runner.github.io) is used and the test suite is large. 

Mocha and Jasmine already support this feature via '.only' and 'iit' respectively. 

What do you guys think?

**Comment by leobalter** [comment]
As on #766 and now I'm bringing the conversation here, I proposed the implementation of `QUnit.only`

Previous arguments were:

> Based on feedback from other developers, I'm proposing `QUnit.only` to run just a single test block.

> `QUnit.only` implementation would be similar to `QUnit.test` but when registered to the tests queue, it would be flagged as the only valid test to run.

> The behaviour should be like the `rerun` feature, but instead of using a browser interface, it would allow QUnit to run that single flagged test on other interfaces, like headless browsers (PhantomJS) and Node-like environments.


@JamesMGreene asked a very reasonable question:

> What should happen if there is more than 1 instance of `QUnit.only`?
 - Run multiple (makes the name `only` feel a little weird but not unreasonable)
 - Run the first one but log a special global assertion failure for any additional instances
 - Don't run any of them and log a special global assertion failure for all instances 
 - Something else?

I believe the best option is to make it work **only** for the first `only` call, all the remaining regular tests and `only` should be **ignored** in the run. As this is a method to help the development process only, we shouldn't care to trigger any failure in this one.

**Comment by jzaefferer** [comment]
Would you also make any changes in the HTML reporter? Maybe a badge similar to the one for `QUnit.skip`?

As for the exclusiveness, would be good to check other implementations like Jasmine and Mocha.

**Comment by jzaefferer** [comment]
Meanwhile I've got to use Mocha on a project and got quickly annoyed by two implementation details of their `only` feature: It will only run the first `only` describe/it, and ignore others, unless they have the same name (probably not intended behaviour, but happend once due to copy-pasta). When I needed it, having it run all `only`s would've been much more useful. Its also annoying to have to remember to undo these changes in the code before committing. So far I've ended up with `only` in master just once...

I can see how CLI-based filter won't mix well with a watcher task, but still feel like this is the wrong solution. I'd like to have a watcher run the test that I just changed first (somewhat similar to QUnit's rerun feature preferring failed tests), then run remaining tests, but without showing the output of passed tests (another annoyance in mocha). That way you don't have to remember to revert source changes, you get fast feedback on the changed test, and you still get feedback from running all tests.

**Comment by ebenoist** [comment]
This feature is the biggest thing I miss from Jasmine. As a code base grows, doing a full test run in an Ember app can mean waiting minutes. During this time the Qunit UI is completely unresponsive or continuously moves focus as it builds and tears down acceptance tests.  Having the equivalent of a `Qunit.only` would mean being able to focus on the task at hand with incredibly fast feedback only to delete that `Qunit.only` when you're confident in the correctness of your current unit of work.

Currently I use the module selector in the Qunit UI to accomplish something like this, but this can be incredibly clumsy as I need to wait for the full run to complete before the UI is responsive enough to select a specific module. This action also takes me away from the code I'm actually writing.

Please reconsider this feature request, as I think its far more important as SPA Qunit test runs become more and more complex.

**Comment by leobalter** [comment]
QUnit.only is a welcome feature. I'll put this on my schedule, but I would also like any contribution to help implementing it.

**Comment by jzaefferer** [comment]
@ebenoist could you help implementing `QUnit.only`?

**Comment by ebenoist** [comment]
I'll see if I can carve out sometime next weekend. Can you point out any conventions I should be aware of, potential designs, or similar concepts already in the `QUnit` codebase?

**Comment by jzaefferer** [comment]
I think the design, including the display in the html reporter, of `QUnit.skip` comes closest to what we're looking for here. It should be fairly simple, so I think we can start with a pull request and go from there. No need for more up front design than what's in this issue.

**Comment by ebenoist** [comment]
Sounds good, I should be able to put up something soon.

**Comment by leobalter** [comment]
@ebenoist, would you also regard the #528 when doing QUnit.only? that would be a ++

**Comment by ebenoist** [comment]
@leobalter I'll take a look. I finally carved out some time for this, I hope to get something up today.

**Comment by leobalter** [comment]
nice! I'm looking forward!

**Comment by ebenoist** [comment]
So after looking at this for a bit, the simplest way to accomplish this would probably be to set the filter and clear out the current config.queue:

```JavaScript
// Will be exposed as QUnit.only
function only( testName, expected, callback, async ) {
	var newTest;

	if ( arguments.length === 2 ) {
		callback = expected;
		expected = null;
	}

	newTest = new Test({
		testName: testName,
		expected: expected,
		async: async,
        only: true,
		callback: callback
	});

    QUnit.config.queue.length = 0;
    QUnit.config.filter = newTest.module.name + ": " + newTest.testName;

    newTest.queue();
}
```

For the reporter I can then list the number of tests skipped by doing Test.count - 1. And do some custom styling to show that the test was the only test being ran.

For testing I should be able to make sure that this test module runs first and then clears the filter manually to allow the remaining tests to run as normal.

Something like this:

```JavaScript
QUnit.module( "QUnit.only");

QUnit.test( "implicitly skipped test", function( assert ) {
  assert.ok( false, "test should be skipped" );
});

QUnit.only( "only run this test", function( assert ) {
  assert.ok( true, "only this test should run" );
});

QUnit.config.filter = [];
```

I can modify the reporter to display the test in the following fashion:
<img width="688" alt="screen shot 2015-10-08 at 1 43 58 pm" src="https://cloud.githubusercontent.com/assets/1656713/10377828/adbc9d54-6dc2-11e5-9649-84b995aa249b.png">

This approach should also allow for programatic module filters in the future if needed.

Thoughts on this approach?

**Comment by jzaefferer** [comment]
That sounds good to me.

**Comment by leobalter** [comment]
The method implementation seems great.

For the tests we can isolate it on a different html file, repeating the failing tests after the `only` call and in other modules.

Also it is good to include a successive `only` call with a failing test, this way we make sure only the first registered `only` will run.

---

Regarding the module approach: it might be good to discuss it with the nested modules as well. With the callbacks, my wish is to allow a `QUnit.only` replacing a module and running all the tests inside that module. That requires a further work to make `QUnit.module` and `QUnit.test` similar.

cc @gibson042 (about my last paragraph).

**Comment by ebenoist** [comment]
Great! I should be able to polish this up over the weekend or by early next week. I'll hold off on any module changes, but I really like the idea of using QUnit.only as a stand-in for a module as well. I think isolating modules is really where this feature begins to really shine. With that said, I'll put a PR up for just the simple case and we can iterate into something more robust.

Thanks for the feedback.

**Comment by leobalter** [comment]
> I think isolating modules is really where this feature begins to really shine.

Agreed

The nested modules are already on the master branch, but having a PR for tests only will make it faster for a first release.

**Comment by gibson042** [comment]
@leobalter Sounds exciting! I think the biggest hurdle will be addressing the synchronously-invoked `module` callback vs. asynchronously-invoked `test` callback, but that looks tractable to me.

**Comment by leobalter** [comment]
@ebenoist I'm very excited and looking forward to see your implementation. I would love to see your PR.
