### ISSUE TITLE
There is no visual indication when you're focused on a single test

### ISSUE THREAD

**Issue by mimshwright** [jquery/qunit#528]
When you double-click on a test to run only that test, there is no indication that you are only running a single test except for the URL. As you can see from the popularity of [this StackOverflow ticket](http://stackoverflow.com/questions/13752715/qunit-is-only-running-the-first-test/13753426#13753426), this is confusing for more people than just myself. 

I propose that the page offer some indication that you're running a single test and show a link to go back to the full suite.

**Comment by platinumazure** [comment]
I might work on something. Just out of curiosity, what would people think about a module link as well?

So basically, if you run a test page with `testId=...`, it would generate a "Run [module name] tests" link and a "Run all tests" link. If you run a test page with `module=...`, it would generate a "Run all tests" link. Of course, it gets a little more complicated when multiple modules and/or testIds are specified, but I'm sure we could come to some reasonable design on this.

**Comment by jzaefferer** [comment]
@platinumazure I'm not sure what you have in mind there, for the UI. That seems a separate design from the "greying out" discussed above. Anyway, would be great if you could put together a prototype.

**Comment by platinumazure** [comment]
Um, yes, that's technically true. It just seemed to be a natural
consequence of that single-test focus. I'll open a new issue or PR though
since my proposal is technically not dependent on this one.

**Comment by jzaefferer** [comment]
Okay, thank you. I'm definitely interested in exploring other options to address the original issue!
