### ISSUE TITLE
Expose version in API and display in html reporter

### ISSUE THREAD

**Issue by Krinkle** [jquery/qunit#554]
It would be helpful when working on a project to more easily identify what version of QUnit is being used (e.g through a property on the `QUnit` object).

While at it, maybe also display it somewhere in the html reporter (near where we dump the user agent).

**Comment by shivamdixit** [comment]
@Krinkle @jzaefferer Please review the PR.

**Comment by jzaefferer** [comment]
Btw. there's no need to ask people to review a PR just after you've sent it. Watchers of the repo get notifications anyway.
