### ISSUE TITLE
Investigate removing QUnit.config.autorun

### ISSUE THREAD

**Issue by JamesMGreene** [jquery/qunit#660]
From a cursory glance through the codebase, I'm pretty sure that `QUnit.config.autorun` really isn't necessary if we make some other updates.

It is also not officially documented, though you can definitely find a few [blog posts](https://twoguysarguing.wordpress.com/2010/11/02/make-javascript-tests-part-of-your-build-qunit-rhino/) about people leveraging it to make their QUnit tests work on Rhino. As such, I'd suggest we leave it in till `v2.x`.

**Comment by leobalter** [comment]
I was able to remove it. Patch is on the way
