### ISSUE TITLE
Collapse failed tests in HTML reporter

### ISSUE THREAD

**Issue by mmun** [jquery/qunit#664]
Often when I have many failing tests I like to collapse the failed tests with something like

```
$('.fail .qunit-assert-list').addClass('qunit-collapsed');
```

This let's me quickly scan and find the simplest failing tests that I should be working on first.

It would be great if this feature were officially added somewhere in the UI.

**Comment by shivamdixit** [comment]
@leobalter Are you working on this issue?

**Comment by jzaefferer** [comment]
Work in progresS: #769

**Comment by nlfurniss** [comment]
@jzaefferer from https://github.com/qunitjs/qunit/issues/664#issuecomment-55515813: `That sounds like a usecase we can optimize for, though I'd prefer a solution that doesn't require an extra button or similar.`

I'd also love to be able to see the stacktraces for all failing tests; could you be persuaded this is a good idea?

**Comment by jzaefferer** [comment]
@nlfurniss please create a new issue with a bit more context and background. A 4 year old quote in a closed ticket is not enough to kick anything off.
