### ISSUE TITLE
Show source location of passed tests

### ISSUE THREAD

**Issue by jzaefferer** [jquery/qunit#706]
Every now and then I'm looking at a green suite and want to know where the source for a specific test is located. We capture that information already, for all tests, but only output it when a test fails. We could always output for non-collapsed tests, or only for non-collapsed passing tests (since failing tests will output it already in some way).

**Comment by leobalter** [comment]
By the passing tests you mean print the source location for each passed assertion, right?

With the global assertions, the test might not be enough for this. A assertion location is more precise.

**Comment by jzaefferer** [comment]
No, I meant test. We already capture that information, so would just have to output it.

**Comment by sammyshj** [comment]
I would like to work on this issue.

**Comment by shivamdixit** [comment]
Hey Sambuddha, I think @gauravmittal1995 has already worked on the issue.
Refer #758

**Comment by sammyshj** [comment]
Thanks for pointing that out @shivamdixit

**Comment by jzaefferer** [comment]
This has been addressed in 9498355593a1284720e8accfbf6f37f72cc82a9b (didn't include a ticket reference)
