### ISSUE TITLE
Discussion: Move to es6 modules to build QUnit

### ISSUE THREAD

**Issue by jzaefferer** [jquery/qunit#707]
We should consider using es6 modules to build QUnit, moving from source concatenation to a standard format. The biggest issue with transpiling to es6 are dependencies, but since QUnit bundles its dependencies anyway, we don't have to care about that. There shouldn't be a difference for users either, since the built files would look mostly the same as they do now.  If that works out, we could also use other es6 features in the QUnit source. 

Currently our tests don't need a build step, which we may want to keep. If compilation is fast enough, we could move those to es6 as well, if there are obvious benefits.

Some background and examples: https://medium.com/@brianleroux/es6-modules-amd-and-commonjs-c1acefbe6fc0 (which mostly uses a transpiler *and* browserify, not exactly what we'd want)

**Comment by jzaefferer** [comment]
This should use https://www.npmjs.com/package/rollup for the bundling.

**Comment by JamesMGreene** [comment]
Why not just switch wholesale to Babel?

**Comment by mzgol** [comment]
There's still a question of bundling. Babel can transpile ES6 modules to SystemJS, AMD or CommonJS but you still need to somehow bundle it all up and it's better to choose a method that doesn't introduce a lot of overhead. rollup seems to gain momentum now.

**Comment by mikesherov** [comment]
At Behance, we use es6, with karma, Babel, and webpack to run our test suite. 

Not sure if QUnit is architected in a way to allow preloaders for code, but perhaps that's where you start: 

1. building infra that allows QUnit to use webpack + Babel or even Babel directly when loading test suites.
1. Use that infra to begin authoring QUnit and its test suite in ES6.
1. Release both.

**Comment by mikesherov** [comment]
Why rollup over webpack?

**Comment by mikesherov** [comment]
FYI, webpack has a decent comparison chart of all the different options: https://webpack.github.io/docs/comparison.html

They're the only one who followed @scottgonzalez's recommendation that "if you're going to exist, have a comparison chart explaining why you're existence is necessary".

**Comment by trentmwillis** [comment]
I'm planning to pursue actually doing this. After looking at webpack and rollup (and some others), I'm going to explore using rollup as I think it most closely fits our current setup.

It looks like it'll probably be a large amount of work to get everything setup to work as modules because even though `src` is split up into files, they don't really act like modules with boundaries right now.
