### ISSUE TITLE
Uncaught TypeError: Cannot set property 'innerHTML' of null at qunit:2638

### ISSUE THREAD

**Issue by martin-g** [jquery/qunit#716]
I've just updated from 1.15 to 1.16 and one of my tests fail with:

`Uncaught TypeError: Cannot set property 'innerHTML' of null` at qunit.js:2638

At line 2638 in qunit.js I see:
```javascript
if ( tests ) {
  id( "qunit-testresult" ).innerHTML = html;
}
```

Until now I've used markup template like:
```html
<body>
	<h1 id="qunit-header">Wicket Ajax tests</h1>
	<h2 id="qunit-banner"></h2>
	<div id="qunit-testrunner-toolbar"></div>
	<h2 id="qunit-userAgent"></h2>
	<ol id="qunit-tests"></ol>
       <div id="qunit-fixture"></div>
```

Looking at http://qunitjs.com/ I see that now the template should be just:
```html
<body>
  <div id="qunit"></div>
  <div id="qunit-fixture"></div>
```

This fixed my test !

Problem 1) I didn't see a HEADS UP about this change in a minor release
Problem 2) Now the header says "All tests". Is there a way to use "Wicket Ajax tests" as before ? 
Problem 3) The `qunit-header` is no more a link. `qunit-banner` contains a link but it is not clickable because it doesn't have text child element:
```html
<h2 id="qunit-banner" class="qunit-pass"><a href="http://localhost/ajax-tests/test/js/all.html"></a> </h2>
```

**Comment by JamesMGreene** [comment]
> Problem 3) The qunit-header is no more a link. qunit-banner contains a link but it is not clickable because it doesn't have text child element:

Turns out this was actually broken in `1.15.0` as well, so I'm guessing you actually upgraded from `1.14.0` to `1.16.0`...?

**Comment by JamesMGreene** [comment]
PR #716 submitted for review.

**Comment by martin-g** [comment]
> Turns out this was actually broken in 1.15.0 as well, so I'm guessing you actually upgraded from 1.14.0 to 1.16.0...?

No, I upgraded from 1.15.0 to 1.16.0, but I haven't noticed before.

**Comment by JamesMGreene** [comment]
Ah, gotcha.
