### ISSUE TITLE
HTML Reporter Failure Assertion Source Location Regression On File System

### ISSUE THREAD

**Issue by tntim96** [jquery/qunit#721]
In QUnit 14, the HTML reporter would list the failed test assertion source location at the point in the user's test when run from the file-system. In QUnit 15 it seems to have disappeared, and in 16 and edge, it reports it in the QUnit infrastructure code. For an example, see [qunit-code-fail.html](https://github.com/tntim96/JSCover-maven-plugin/blob/master/plugin-parent/data/src/test/javascript/qunit-code-fail.html). The following versions have the following source outputs:

Version | Assertion source output
--------- | ------------------------------
1.14.0 | @file:///JSCover-maven-plugin/plugin-parent/data/src/test/javascript/spec/qunit-code-fail-spec.js:3:1
1.15.0 | No source is reported
1.16.0 | applyCurrent/<@file:///JSCover-maven-plugin/plugin-parent/data/src/test/javascript/lib/qunit/qunit-1.16.0.js:1951:5
git-current | applyCurrent/<@file:///JSCover-maven-plugin/plugin-parent/data/src/test/javascript/lib/qunit/qunit-git.js:1933:5

**Comment by jzaefferer** [comment]
I just opened QUnit's own `test/index.html` from the local file system in Chrome and Firefox and modified one test to fail. Both report the source correctly like this:

```
Source:     at file:///Users/jza/dev/qunit/test/test.js:14:7
```

If you can provide a reduced test page, we can look into this again, but digging through third-party code is not an option.
