### ISSUE TITLE
Don't ignore bower.json in bower.json

### ISSUE THREAD

**Issue by justinbmeyer** [jquery/qunit#723]
`bower.json` includes important metadata about the package, namely the [main entry point](https://github.com/jquery/qunit/blob/master/bower.json#L12).  

Can you remove `bower.json` from the [ignore list](https://github.com/jquery/qunit/blob/master/bower.json#L12)?  

This will enable things like RaveJS, StealJS, and other module loaders to know how to load QUnit without configuration.

Thanks!

**Comment by jzaefferer** [comment]
Done. Will be available with the next release.
