### ISSUE TITLE
1.17.0 & phantomjs

### ISSUE THREAD

**Issue by jdalton** [jquery/qunit#732]
Heads up, I'm seeing tests hang when using phantomjs as `phantomjs test.js`. It looks like things are getting exported correctly and the `QUnit.load()` is getting called. I'll know more this evening when I dig-in fully.

**Comment by SomethingSexy** [comment]
I might be getting something similar.  My problem stemmed from the toolbarModuleFilter method in released version of qunit.js.  It looks like that method is not checking to see if "qunit-testrunner-toolbar" was created.  The other methods that get called inside QUnit.begin check to make sure the element was created before working on it.
