### ISSUE TITLE
async in beforeEach support

### ISSUE THREAD

**Issue by mateuszf** [jquery/qunit#739]
I'm trying to use 'async' in 'beforeEach' to wait for promise to finish.
I see that QUnit.start() and QUnit.stop() were deprecated and 'beforeEach' does not get 'assert' as its parameter.

How this can be done ? And if not, why ?

**Comment by JamesMGreene** [comment]
Two things:

 1. As of `v1.16.0`, the `beforeEach`/`afterEach` callbacks **do** both get passed the `assert` object for the first parameter as well, so you can use [`assert.async()`](http://api.qunitjs.com/async/). It is just missing from the documentation.

```js
(function(module, test, $) {
  module("example", {
    beforeEach: function(assert) {
      $.ajax("/foo.bar").then(assert.async());  // <---
    }
  });
  test("example test", function(assert) {
    assert.ok(true, "blah");
  });
})(QUnit.module, QUnit.test, jQuery);
```

 2. As of `v1.16.0`, the `beforeEach`/`afterEach` **and** `test` callbacks were all made Promise-aware (for their return value). If the Promise is created/available during the _synchronous_ execution of the callback, then you can just `return` the `then`-able Promise object. See the documentation for [`QUnit.test`](http://api.qunitjs.com/QUnit.test/) for a little more info and [an example](http://api.qunitjs.com/QUnit.test/#example-1).

**Comment by JamesMGreene** [comment]
- Issue 1 recorded as https://github.com/jquery/api.qunitjs.com/issues/96
 - Issue 2 recorded as https://github.com/jquery/api.qunitjs.com/issues/95

**Comment by mateuszf** [comment]
This is great, just tested it with returning value as a promise and it worked flawlessly. Thanks!

**Comment by JamesMGreene** [comment]
:+1:
