### ISSUE TITLE
Invalid filter comparison results in no tests being run.

### ISSUE THREAD

**Issue by lobacten** [jquery/qunit#742]
In qunit/src/test.js on line ~346 there is this code:
```
if ( fullName.indexOf( filter ) !== -1 ) {
	return include;
}
```
Which is doing a comparison of an unmodified `filter` var against a lower cased `fullName` var:
```
fullName = ( this.module.name + ": " + this.testName ).toLowerCase();
```
Thus tests with capital letters can't be matched.

Two options for fixes...

Case Sensitive filters:
```
fullName = ( this.module.name + ": " + this.testName );
```
Case Insensitive filters:
```
filter = config.filter.toLowerCase();
```

**Comment by leobalter** [comment]
Fixed by #753
