### ISSUE TITLE
All Test Results are not showing in test window, Only 1st and last appearing

### ISSUE THREAD

**Issue by rahulsahay19** [jquery/qunit#743]
Hi Team,

I have used qunit to write the API Tests. However, when i run all tests in that case it will show only 1st and last test case result. For others it simply show empty containers. However, i am getting results for all tests. I have attached screen shot for your reference.  Kindly, let me know if i am doing any thing wrong some piece needs to be updated.

![qunit1st](https://cloud.githubusercontent.com/assets/3886381/6035800/eba6c43e-ac5f-11e4-85f7-13e322ecdf0f.png)

![qunit2nd](https://cloud.githubusercontent.com/assets/3886381/6035805/f5d929e2-ac5f-11e4-8bd4-01c633502b73.png)

Thanks,
Rahul

**Comment by JamesMGreene** [comment]
It's nothing that I've seen before, unless your tests just don't have assertions. You can always turn on `QUnit.config.requireExpects = true;` (see http://api.qunitjs.com/QUnit.config/ for more info) and then use `assert.expect(myNumberOfExpectedAssertions)` within your test body to help diagnose if all of the expected assertions are indeed being executed.

Can you make a JSBin that reproduces the problem (as closely as possible) and/or share your test page's HTML and the JS for at least 1 failing and 1 "passing" (not running) test?

What version of QUnit are you running?  If your tests are invoking asynchronous calls to those APIs, you should definitely try to use the latest QUnit if at all possible as we solved some important async testing bugs/inconsistencies in `v1.16.0` (and then fixed some other regressions in the `v1.17.x` series).

**Comment by rahulsahay19** [comment]
Thanks James. After your suggestion it started working.

On Wed, Feb 4, 2015 at 9:59 PM, James M. Greene <notifications@github.com>
wrote:

> It's nothing that I've seen before, unless your tests just don't have
> assertions. You can always turn on QUnit.config.requireExpects = true;
> (see http://api.qunitjs.com/QUnit.config/ for more info) and then use
> assert.expect(myNumberOfExpectedAssertions) within your test body to help
> diagnose if all of the expected assertions are indeed being executed.
>
> Can you make a JSBin that reproduces the problem (as closely as possible)
> and/or share your test page's HTML and the JS for at least 1 failing and 1
> "passing" (not running) test?
>
> What version of QUnit are you running? If your tests are invoking
> asynchronous calls to those APIs, you should definitely try to use the
> latest QUnit if at all possible as we solved some important async testing
> bugs/inconsistencies in v1.16.0 (and then fixed some other regressions in
> the v1.17.x series).
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/jquery/qunit/issues/743#issuecomment-72886615>.
>



-- 

   [image: --]

rahul sahay
[image: http://]about.me/rahulsahay19
   <http://about.me/rahulsahay19?promo=email_sig>

**Comment by rahulsahay19** [comment]
closing the issue
