### ISSUE TITLE
Add assert.notOk() function

### ISSUE THREAD

**Issue by piranna** [jquery/qunit#744]
The same way that equal(), deepEqual(), propEqual() and strictEqual() has their negative versions, ok() should have a notOk() negative version to check for falsy values, in a more clean and explicit way that by adding a negation operator in front of the value to check.

```Javascript
assert.ok(!value)
assert.notOk(value)
```

**Comment by leobalter** [comment]
The `assert.notOk` seems better to go as an extension. It's not necessary to include this assertion in the API as it aims to keep itself simple.

`not[Equal|DeepEqual|PropEqual|StrictEqual]` has some more specific cases and I would be more inclined to remove them, but that would break the retrocompatibility and they're already there.

**Comment by JamesMGreene** [comment]
I would love to get a negation property implemented, e.g. `assert.not`, `assert.not.not == assert`.

**Comment by leobalter** [comment]
Ok, I'm reopening it.

**Comment by leobalter** [comment]
I searched and saw the other assertion libraries does have the same `assert.notOk` method. Some of then was [tape](https://github.com/substack/tape#tnotokvalue-msg) and [chai](http://chaijs.com/api/assert/).

I've also talked with some other developers and it seems the `.notOk` would improve readability for other developers. 

One thing I noticed during those conversations that makes QUnit great for me is being one of the JS testing libraries with the fewest assertions in it's API, making it simple. That's why I'm not 50/50 to decide which way to go, and we also have positive perspective from @JamesMGreene.

More opinions, please.

**Comment by JamesMGreene** [comment]
For the record, I would be accepting of an `assert.notOk` for readability's sake.

**Comment by piranna** [comment]
> For the record, I would be accepting of an assert.notOk for readability's sake...

That's the main reason why I proposed it :-) Also, it makes it more orthogonal with the other assert methods, that have their negative version.


> but would much rather implement a negation property and eliminate all of the not* assertions both in QUnit core and for custom assertion extensions.

I'm not too much into this kind of literate properties since at my opinion makes the code more verbose and ofuscate (behaviour-driven libraries abuse of this and I'm not always sure if I'm writting a valid word or not), but if this is the only case mostly as a namespace and makes simpler the code, I think is not a bad alternative... :-)

From an implementer point of view, in Python is trivial to automagically negate and route all the calls done on the namespace also for custom asserts, but on Javascript would require to use Proxy objects. Another alternative would be to fill the ```.not``` namespace on start with the methods found in the assert object, but this would still has the problem of the custom asserts after that (Object, observe(), maybe?).

**Comment by jzaefferer** [comment]
I'm okay with adding `assert.notOk`. That would be a pretty simple change, while supporting `assert.not` might get much more complicated. PRs for the one or the other would help.

**Comment by piranna** [comment]
Quick pull-request done.

**Comment by Krinkle** [comment]
I'd like to challenge the `ok` and `not*` assertions. I think they're a bad practice. Putting them together seems a step backwards. I'd rather we discourage them as a "Bad Part". Perhaps kept for backwards compatibility; and parity with CommonJS' Unit Testing spec (which I believe was inspired by QUnit, awkward..).

Using `ok()` indicates one of two problems:
* The software (or testing strategy) is unreliable. (Unsure what value to expect.)
* The author is lazy and uses it as shortcut for a proper comparison.

The former necessitates improvement in the code being tested. The latter comes with two additional caveats:

1.  Less debug information. (No actual/expected diff). Without an expected value provided, one can't determine what's wrong with the value.
2. Masking regressions. Even if the API being tested returns a proper boolean and `ok` is just a shortcut, the day the API breaks (e.g. returns a number, string, array, function, Promise or other object) the test will not catch it.

Common examples:
```js
// Meh
assert.ok( bool );
assert.ok( fn );

// Better?
assert.strictEqual( bool, true );
assert.equal( typeof fn, 'function' );
```

Using `not*()` indicates one of three problems:
* The software is unreliable.  (Unsure what value to expect.)
* The test uses an unreliable environment. (E.g. variable input data, insufficient isolation or mocking.)
* The author is lazy and uses it as shortcut for a proper comparison.

Common example:
```js
var index = list.indexOf( item );
// Meh
assert.notEqual( index, -1 );
// Better?
assert.equal( index, 2 );
```

I've yet to see the first use of `ok` or `not*` that wouldn't be improved by writing it a different way.

I'd love to be proven wrong, so I ask you: What is the added value in `ok` or `not*`?

**Comment by piranna** [comment]
What would you find as a better alternative? Maybe ```assertTrue()``` and ```assertFalse()``` and checking explicitly for Boolean values?

**Comment by scottgonzalez** [comment]
I have some examples that come to mind.

## ok()

I often have tests where I want to verify that a method is called as a result of calling some other method, but there's no input to verify. Using `ok( true, "foo() was called" )` works great for this case. The inverse case also exists: verifying that a method is not called via `ok( false )`. Here's a real example: https://github.com/jquery/jquery-license/blob/3b5c3c57b65fdc61b85528cb95f6df5edf03b939/test/repo.js#L43-L50

## not*()

Let's say you have a widget which takes an array of values and you initialize multiple instances with the same array, but the widget needs to treat the two instances separately. You can currently use `notStrictEqual( widget1values, widget2values )`. If `ok()` and `not*()` were removed, this assertion would become `equal( widget1values === widget2values, false )` which is definitely less expressive.

Another example is testing a method that generates unique values, e.g., a random password generator. I've tested this before by calling the method multiple times and using `notEqual()` on the output.

**Comment by Krinkle** [comment]
@scottgonzalez As said, I agree there are scenarios where a negated comparison is useful and appropriate. Especially for token generators. One could still assert value type and shape, however (e.g. string / length). ([example](https://github.com/wikimedia/mediawiki/blob/579d6e7/tests/qunit/suites/resources/mediawiki/mediawiki.user.test.js#L89-L95))

As for function call tracking, I think using `ok( Boolean )` for that is inferior to strict flow tracking using a counter ([example](https://github.com/wikimedia/oojs/blob/v1.1.5/tests/unit/EventEmitter.test.js#L114-L125)) or array ([example](https://github.com/wikimedia/oojs-ui/blob/v0.8.0/tests/Process.test.js#L26-L40), [example](https://github.com/wikimedia/oojs/blob/v1.1.5/tests/unit/EventEmitter.test.js#L28-L41)). This becomes more important when abandoning the `assert.expect` model, of course, though not required.
