### ISSUE TITLE
test filter input fails without any module

### ISSUE THREAD

**Issue by San4es** [jquery/qunit#748]
Steps to reproduce:
1. Open http://jsfiddle.net/gj6hudry/ sample.
2. Type 'testname' in 'Filter' input and click 'Go'.
3. Error "Cannot read property 'options' of null" will be occurred at:
    selection = decodeURIComponent( selectBox.options[ selectBox.selectedIndex ].value ),

**Comment by leobalter** [comment]
the `Cannot read property 'options' of null` error was caused because no module was present.

I'm fixing it, thanks!
