### ISSUE TITLE
1.17.1 - Filter does not work correctly with upper case letter in test name

### ISSUE THREAD

**Issue by San4es** [jquery/qunit#749]
Steps to reproduce:
1. Open http://jsfiddle.net/nxrLcppq/
2. Type "Test Name" in "Filter" input and click "Go"
3. No any tests will be run

Compare results with "test name" filter string.

Seems, this issue was appeared after https://github.com/jquery/qunit/commit/1d44eb38052d25d97a631b9711e481303fc472b6 , where
    filter = config.filter && config.filter.toLowerCase(),
was replaced by
    filter = config.filter,

**Comment by TheCloudlessSky** [comment]
:+1: This one caused lots of headaches for us since we use capitals in all of our constructor names.
