### ISSUE TITLE
Dump: .name/.message-property doublettes

### ISSUE THREAD

**Issue by bubens** [jquery/qunit#750]
If an Object has the properties .name and/or .message the dump of the object contains a doublette of said properties.
Example: http://jsfiddle.net/c50ndqhq/1/

**Comment by leobalter** [comment]
I reverted the commit, that introduced a new bug omitting innumerable properties.

**Comment by bubens** [comment]
I had the inArray function all wrong. Now all my tests work as they should with enumerable and non-enumerable properties. (http://unpunk.de/bugs/qunit/index-mod.html)

But it seems something's wrong with the CLA again. I give up. I thought this time I had it right...
