### ISSUE TITLE
`testIds` are invalidated when using toolbar options

### ISSUE THREAD

**Issue by lamchau** [jquery/qunit#754]
**Version**: 1.17.1 / 1.17.2-pre

**Steps to repro**:
 1. Specify two (2) `testId` (e.g. `http://localhost:3003/?testId=1a9c4dda&testId=f0342ae5`)
 2. Click/select 'Check for Globals'

**Result**: Test refreshes and the URL is encoded `http://localhost:3003/?testId=1a9c4dda%2Cf0342ae5` and none of the tests run.

**Expected**: Same are repro step 1 but with option flag(s) set.

Related to: #569

**Comment by leobalter** [comment]
@lamchau, your 7069029 seems to solve the problem.

Having two `testId`s set in the url params is not supported, and I don't recommend using it,  Maybe filtering by the module would be better.

Even though, I don't see any reason to not ship your commit.

I'm waiting for the PR.

**Comment by lamchau** [comment]
Thanks! Just signed the CLA! 

I was looking for tests to write for parity with `config.testId = [...]` before I submitted a PR -- but I didn't see any.

**Comment by leobalter** [comment]
We don't have proper tests for the urlParams yet. :(
