### ISSUE TITLE
assert.greaterThan() and assert.lesserThan() needed?

### ISSUE THREAD

**Issue by gauravmittal1995** [jquery/qunit#757]
Is there a need for assert.greaterThan() and assert.lesserThan() function??

I know we can implement them using `assert.ok(a > b, message)`, but according to me its better to have a seperate function for it as many other unit testing frameworks have.

```js
assert.lesserThan( first, second, message );
assert.greaterThan( first, second, message );
```

I can apply the change if needed.

**Comment by Krinkle** [comment]
As part of general testing best practices, I find that tolerant assertions are not good assertions. You should be able to strictly assert what you're expecting.

There are exceptions where (in addition to strict assertions verifying the shape of a value) you might need a negated assertions to assert something is different. But asserting that something is not `-1`, or that a value is greater or lesser than something smells like a problem in the code.

**Comment by jzaefferer** [comment]
Either way, we wouldn't add those assertions to QUnit itself. If you're interested in maintaining a plugin, you could publish that and have it listed on http://qunitjs.com/plugins/

**Comment by JamesMGreene** [comment]
@gauravmittal1995:
Here you go: [JamesMGreene/qunit-assert-compare](https://github.com/JamesMGreene/qunit-assert-compare)

**Comment by gauravmittal1995** [comment]
Thanks @JamesMGreene
