### ISSUE TITLE
Failed assertions throws an AssertionError 

### ISSUE THREAD

**Issue by leobalter** [jquery/qunit#765]
based on http://wiki.commonjs.org/wiki/Unit_Testing/1.0, we could change QUnit to throw an `AssertionError` for failed assertions. 

```js
new assert.AssertionError({message: message, actual: actual, expected: expected})
assert.AssertionError instanceof Error
```

This way, we would not only be closer to a standard but we would be able write proper tests for failed assertions, which we don't have today.

The other side of doing this is not running the following assertions in the same test block. This might be considered as a bad thing, but regarding a test block should more specific, this is not that bad, IMHO.

**Comment by leobalter** [comment]
The other way to test failing assertions would be mocking `QUnit.assert.push`, that would change any feature on QUnit.

The counter argument for this issue is that not throwing an exception on failed assertions is one of the things that make QUnit unique, but I still want to find something to test them properly.

**Comment by jzaefferer** [comment]
CommonJS doesn't matter, so "compatibility with CommonJS" shouldn't be a priority for us.

As for the suggested change, its a common design in other test frameworks, which is a good argument for adopting it. From my point of view its also a user-hostile limitation that we should continue to ignore.

**Comment by leobalter** [comment]
As the #767 is in the process, I'm already solving the final issue I wanted to solve with this before, which is something to test the failing assertions.

After some time rethinking about the exceptions, QUnit is indeed good to not do it, as it doesn't need to be like every other frameworks.
