### ISSUE TITLE
QUnit.only to test only a single test block

### ISSUE THREAD

**Issue by leobalter** [jquery/qunit#766]
Based on feedback from other developers, I'm proposing `QUnit.only` to run just a single test block.

`QUnit.only` implementation would be similar to `QUnit.test` but when registered to the tests queue, it would be flagged as the only valid test to run.

The behaviour should be like the `rerun` feature, but instead of using a browser interface, it would allow QUnit to run that single flagged test on other interfaces, like headless browsers (PhantomJS) and Node-like environments.

**Comment by JamesMGreene** [comment]
What should happen if there is more than 1 instance of `QUnit.only`?
 - Allow multiple (makes the name `only` feel a little weird but not unreasonable)
 - Log a special global assertion failure
 - Something else?

**Comment by jzaefferer** [comment]
I'm pretty sure we've had previous discussions about this, but I can't find any of the tickets. Would be great if someone could try to dig through closed tickets. It would surely help to remember what method name was proposed before...

**Comment by scottgonzalez** [comment]
#496?

**Comment by jzaefferer** [comment]
Yep, thanks. Since that is open, let's continue the discussion there.

**Comment by leobalter** [comment]
I wasn't able to find #496 before. Thanks.
