### ISSUE TITLE
HTML reporter regression: Failed test display messed up

### ISSUE THREAD

**Issue by jzaefferer** [jquery/qunit#771]
Looks like bc9dfd3392cd073cbabafd42ffe4fccfac3db131 (from #737) caused a regression in the HTML reporter when showing failed tests. Here's QUnit's testsuite with two failing tests before the change:

![...](http://bassistance.de/i/56739b.png)

Here's the same testsuite with the same failures after the change:

![...](http://bassistance.de/i/4be56e.png)

/cc @insin since you wrote #737, could you take a look at this regression?

**Comment by jzaefferer** [comment]
@leobalter @shivamdixit @gauravmittal1995 can I interest any of you to look into fixing this regression? This is a blocker for the next release.

**Comment by gauravmittal1995** [comment]
@jzaefferer Sure, i'll check it out

**Comment by gauravmittal1995** [comment]
@jzaefferer Please check https://github.com/jquery/qunit/pull/804 for this.
