### ISSUE TITLE
Splitting core.js into smaller components?

### ISSUE THREAD

**Issue by BraulioVM** [jquery/qunit#782]
Inspecting the source code, it's possible to see that core.js involves several independent components. We could split the file into several other files like:

* **core/utilities.js**: in which we could have functions like ````hasOwn```` or ````objectType````.
* **core/config.js**: in which we could have the ````config```` object.
* **core/reporter.js**: with the logging callbacks...

I think this could help removing the circular dependencies in the project, and that would help to accomplish things like #707 and https://github.com/jquery/qunit/pull/735

**Comment by jzaefferer** [comment]
That sounds good, though I wonder if a `utilities.js` is a good idea - might as well split those functions into individual files.

**Comment by BraulioVM** [comment]
Do you mean having a one file for ````hasOwn````, one file for ````objectType```` and so on? Could you  please elaborate a bit more on that? I'm not sure I understand the point.

I do understand that having a file called ````utilities.js```` may not give any information about what it contains. Anyway, one file for each function seems to much (unless we put them inside a ````core/utilities```` directory, which would give us the same problem I was talking about)

**Comment by jzaefferer** [comment]
I guess it depends on the individual functions. `objectType` is long enough to justify its own file, but various other helpers in `core.js` aren't. Let's start with a `utilities` module for the short ones.

**Comment by BraulioVM** [comment]
I'm working on a PR right now but I got some problems. 

As I'm declaring variables in different files, jscsrc will complain every time it finds variable declaration made in several different places with the same scope. For example. if I declare ````config```` in ````core/config.js```` and ````QUnit```` in ````core/qunit.js````,  jscsrc will tell me I need to join var declarations

Any idea on how to solve this?

**Comment by jzaefferer** [comment]
Yes, by dropping the `onevar` rule: 61fd7fe20f5b0d9e20fabd77831083fc42922dc9

Its a rather recent change in our style guide, most of our projects still use onevar. Now QUnit doesn't anymore, so that error should go away once you rebase.

**Comment by jzaefferer** [comment]
Also had to update `.jscsrc`, since that also checked for `onvar`. Which is what you actually ran into. You've still got one failure from `jscs`, but that is a valid one.
