### ISSUE TITLE
improve grunt watch task

### ISSUE THREAD

**Issue by leobalter** [jquery/qunit#788]
In a private chat I saw @jzaefferer's will to improve speed on our grunt watch task. 

Current options to try (not exclusive):

- grunt-contrib-watch [spawn and interrupt](https://github.com/gruntjs/grunt-contrib-watch#optionsspawn) options.
- [grunt-concurrent](https://www.npmjs.com/package/grunt-concurrent)
- [grunt-newer](https://www.npmjs.com/package/grunt-newer)

Some goals:
- grunt watch needs to be faster
- don't rebuild src files when only test files are modified
- can we use those tools to run jshint/jscs only at the modified files (src or each test files)
- run tests in parallel (if this goes faster)

**Comment by rdugue** [comment]
I made some changes on a branch to run jshint/jscs only modified files but it is actually making grunt watch run ~2 seconds slower for me.  You can see the change I made [here.](https://github.com/rdugue/qunit/blob/issue-788/Gruntfile.js#L193)  I'm going to test some more.

**Comment by leobalter** [comment]
Closed by #886
