### ISSUE TITLE
Warning qunit not compatible with node >= 12

### ISSUE THREAD

**Issue by dhowe** [jquery/qunit#808]
npm WARN engine qunit@0.7.5: wanted: {"node":">=0.6.0 < 0.12.0"} (current: {"node":"0.12.0","npm":"2.5.1"})

**Comment by JamesMGreene** [comment]
That's not our package, please file an issue with [kof/node-qunit](https://github.com/kof/node-qunit).

If you would like to use raw QUnit on Node.js, than you want the package named "qunitjs" instead.

**Comment by dhowe** [comment]
ah yes, I see that now, though I'm not using node-qunit directly (and it isn't listed as a dependent of anything on npm) -- any idea where its coming from?

  "devDependencies": {
    "argsparser": "0.0.6",
    "del": "^1.1.1",
    "gulp": "^3.8.11",
    "gulp-concat": "^2.3.3",
    "gulp-jshint": "^1.7.0",
    "gulp-qunit": "^1.2",
    "gulp-rename": "^1.2.0",
    "gulp-replace": "^0.4.0",
    "gulp-scp": "0.0.3",
    "gulp-symlink": "^1.1.0",
    "gulp-task-listing": "^0.3.0",
    "gulp-uglify": "^0.3.1",
    "qunit": "^0.7",
    "qunitjs": "^1.14.0",
    "yargs": "^3.4.5"
  }

**Comment by leobalter** [comment]
The "qunit" package on npm is the node-qunit package. As James said, use qunitjs for the raw qunit.

**Comment by dhowe** [comment]
got it, thanks much
