### ISSUE TITLE
1.18.0 breaks phantomjs tests.

### ISSUE THREAD

**Issue by jdalton** [jquery/qunit#818]
I noticed when I updated to 1.18.0 my phantomjs tests started not ending with zero test runs.
See https://travis-ci.org/lodash/lodash-amd/builds/61941189.

Once I reverted to 1.17.1 things started working again.
See https://travis-ci.org/lodash/lodash-amd/builds/62009692

**Comment by jdalton** [comment]
Narrowed it down to this change https://github.com/jquery/qunit/compare/1.17.1...1.18.0#diff-5b7e94e2a10b848c4ae4b539388f86aeL728.

**Comment by jdalton** [comment]
Seems this commit broke it https://github.com/jquery/qunit/commit/d6baf223d9329cb880457b87bacad86842717fea.

**Comment by jdalton** [comment]
On further digging its related to when phantomjs is not running a web site so when script have access to `phantom` object. There is also a `document` object with a `readyState` of `complete`. So when it hits the `addEvent( window, "load", QUnit.load );` it's ignored. With QUnit 1.18.0 it now starts QUnit in this mode where before it left it up to scripts to call `QUnit.load()`.

**Comment by jdalton** [comment]
The check could be modified to:
```js
if ( typeof phantom == 'undefined' && document.readyState === "complete" ) {
```
To solve the early initialization issue.

**Comment by jzaefferer** [comment]
Thanks for tracking down the issue, that certainly helps.

> It's related to when PhantomJS is not running a web page so when script can access the phantom object. There also happens to be document object with a readyState of complete.

Can you help us reproduce this setup with a simplified test setup? That would allow us to test your suggested solution and evaluate alternatives, and prevent future regressions.

**Comment by jdalton** [comment]
```bash
$ phantomjs
phantomjs > var QUnit = require('path/to/qunit')
phantomjs > QUnit.config.pageLoaded
true
```

**Comment by jzaefferer** [comment]
@leobalter could you take a look at this? Maybe there's an alternative to checking specifically for `phantom`?

**Comment by leobalter** [comment]
checking if a global `phantom` is undefined only is not good. I would rather won't take the risk to break other sites/apps using this name.

I'm setting a deeper check based on the [phantomjs documented api](http://phantomjs.org/api/phantom/property/version.html) to prevent the issue reported here.

**Comment by kenips** [comment]
@leobalter looking forward to this fix here. Any milestone for 1.18.1 or any blocker for it that needs help with?

**Comment by leobalter** [comment]
@kenips QUnit 1.19 is about to be released with this fix.

cc @jzaefferer

**Comment by kenips** [comment]
:+1: thanks the great work guys!
