### ISSUE TITLE
Hide passed tests does not work on page reload

### ISSUE THREAD

**Issue by NoelAbrahams** [jquery/qunit#819]
Hi,

Version: 1.18.0/1.18.1-pre

* Start with 'Hide Passed Tests' unchecked and refresh the page.
* Check 'Hide Passed Tests'. This causes all passed tests to collapse, as expected.
* Now reload the page. At this point 'Hide Passed Tests' is checked, but passed tests are not hidden.

**Comment by jzaefferer** [comment]
I tested this with 1.18.0 and master, I'm unable to reproduce the issue.

What browser are you using? Any other detail that you can provide?

**Comment by NoelAbrahams** [comment]
Chrome  42. Does the code depend on anything in local storage?

**Comment by jzaefferer** [comment]
Not for this feature. The `hidepassed` flag is stored in `window.location` (updated via `window.history.replaceState` where available).

**Comment by NoelAbrahams** [comment]
I think that might be the problem. Can the code not read the query string every time? To the user it appears that the query string has "hidepassed", which implies everything should work. What I mean to say is that the query string is the actual store - there should be no need to save it elsewhere.

**Comment by jzaefferer** [comment]
The flag is stored in the query string, no where else. There are other QUnit features that use `sessionStorage`, but not this one. You can look at the code for `hidepassed` to verify that yourself.

**Comment by NoelAbrahams** [comment]
> The flag is stored in the query string, no where else.

But I though you said it's stored in `window.location`? Can that not be overwritten by some user code?

**Comment by jzaefferer** [comment]
The query string is part of the [`location`](https://developer.mozilla.org/en-US/docs/Web/API/Window/location) property.

Guessing like this is no going to get us anywhere, we need to be able to reproduce the issue.

**Comment by NoelAbrahams** [comment]
Quoting from the link:

> Though Window.location is a read-only Location object, you can also assign a DOMString to it. This means that you can work with location as if it were a string in most cases: location = 'http://www.example.com' is a synonym of location.href = 'http://www.example.com'

That would mean that users are able to write `window.location = 'http://foobar'`. So `location` should not ideally be used to store state.

**Comment by jzaefferer** [comment]
Doing that will load a different page, so there is no more QUnit testsuite. That makes no sense.

**Comment by NoelAbrahams** [comment]
Yes, that's a fair point. I'll take a look to see where it's failing.

**Comment by NoelAbrahams** [comment]
Just came around to look into this. The problem above can be reproduced by removing the element with id `qunit`.

Basically, we wanted to have our own header, so we had manually added the following HTML to the page:

```html
   <!--
    <div id="qunit"></div>
   -->
    <h1 id="qunit-header">
          // Custom header here
    </h1>
    <div id="qunit-testrunner-toolbar"></div>
    <ol id="qunit-tests"></ol>
```

This actually works, except that `hidepass` is not honoured.

The problem code is the following in `QUnit.begin`

```JavaScript

	if ( qunit && config.hidepassed ) {
		addClass( qunit.lastChild, "hidepass" );
	}

```

This code is inconsistent, because the `hidepass` is actually in `qunit-testrunner-toolbar` and existence of that element should imply that the code runs correctly. Probably

```
	addClass( qunitToolbar.parentElement.lastChild, "hidepass" );
```

**Comment by jzaefferer** [comment]
Thanks, I've filed #896 to track that issue.
