### ISSUE TITLE
QUnit IntelliSense for Eclipse, Sublime, Emacs, Vim, Web Editor CodeMirror

### ISSUE THREAD

**Issue by angelozerr** [jquery/qunit#820]
Just for your information I have generated from your doc API a [ternjs](http://ternjs.net/doc/demo.html) plugin https://github.com/angelozerr/tern.jqueryapi/blob/master/qunit1-19.js

tern is a JavaScript inference engine which gives support for completion, hover, etc and can be used with a lot of JavaScritpt Editor like Eclipse, Sublime, Emacs, Vim, Web Editor CodeMirror. Here a screenshot with QUnit completion & Eclipse : 

![QUnit Assert Completion](https://github.com/angelozerr/tern.java/wiki/images/EclipseIDE_QUnitCompletionAssert.png)

For Eclipse users, please read https://github.com/angelozerr/tern.java/wiki/Tern-&-QUnit-support

**Comment by jzaefferer** [comment]
Looks good! Could you add this to our plugins page? https://github.com/jquery/qunitjs.com/blob/master/pages/plugins.html

**Comment by angelozerr** [comment]
> Looks good! 

Glad it seems please you. You can play with the online demo http://demo-angelozerr.rhcloud.com/CodeMirror-Java/qunit.html which uses teh qunit tern plugin with Web Browser CodeMirror.

> Could you add this to our plugins page?

Done with https://github.com/angelozerr/qunitjs.com/commit/10a329951c331192568e5ca59c9468cf2a346871
