### ISSUE TITLE
Fixtures not being restored every time

### ISSUE THREAD

**Issue by vmanjunath** [jquery/qunit#821]
I'm new to QUnit and I might be doing something silly.

 As I understand it, everything in the fixture is reset before a new test is run. However, I'm seeing (what is to me) something strange. In the below example, there's a form in the fixture which consists of just an input element and a `div` with the class `has-error`. So as I understand, before each test is run, these should be restored to their original state. I've specified a `keypress` event handler for `$('input')` to just hide the `div` in the fixture.

I have two identical tests which test this event handler: they trigger a `keypress` on the input and assert that error text is hidden.

What I see is that only one of the two tests ever passes and they switch (so it alternates between test 1 passing and test 2 passing). Is this expected behavior?

    <html>
      <head>
        <link rel="stylesheet" href="qunit-1.18.0.css">
      </head>

      <body>
        <div id="qunit"></div>
        <div id="qunit-fixture">
          <form> 
            <input name="text" />
            <div class="has-error">Error text</div>
          </form>
        </div>

        <script src="http://code.jquery.com/jquery.min.js"></script>
        <script src="qunit-1.18.0.js"></script>
        <script>
          QUnit.test( "test 1", function ( assert ) {
            $('input').trigger('keypress');
            assert.equal($('.has-error').is(':visible'), false);
          });

          QUnit.test( "test 2", function ( assert ) {
            $('input').trigger('keypress');
            assert.equal($('.has-error').is(':visible'), false);
          });

          $(document).ready(function () {
            $('input').keypress(function() {
              $('.has-error').hide();
            });
          });

        </script>

      </body>
    </html>

One more thing that I'm confused about is this: if I add a `click` event handler for `$('input')` and switch the second test to trigger a `click` instead, QUnit gets stuck switching "no try-catch" and "hide passed tests" on and off over and over.

This can't possibly be expected behavior, right? Even if I've done something dumb, I don't see why you'd want anything but either a pass or a fail for your tests to come from QUnit.

**Comment by leobalter** [comment]
on `$('input')` you're selecting every input element inside the reporter, including the no *try-catch* and *hide passed tests* checkboxes. If you want to run tests related to your app behaviour/functionallity within the reporter context and select them via the DOM, be sure to use the `#qunit-fixture` context when selecting your elements.

e.g.: `$('#qunit-fixture').find('input')`

**Comment by leobalter** [comment]
If you have any other question on this topic, you can use this same issue. I closed as it's not an actual QUnit bug.

**Comment by vmanjunath** [comment]
Awesome! Thanks so much.

**Comment by vmanjunath** [comment]
Thanks a lot for the quick response. I think that clearly addresses my second question about the inputs being clicked. But the issue with the two tests alternating between passing and failing still persists. 

     <div id="qunit-fixture">
      <form> 
        <input name="text" />
        <div  class="has-error">Error text</div>
      </form>
    </div>

    <script src="http://code.jquery.com/jquery.min.js"></script>
    <script src="qunit-1.18.0.js"></script>
    <script>
      QUnit.test( "test 1", function ( assert ) {
        $('#qunit-fixture').find('input').trigger('keypress');
        assert.equal($('#qunit-fixture').find('.has-error').is(':visible'), false);
      });

      QUnit.test( "test 2", function ( assert ) {
        $('#qunit-fixture').find('input').trigger('keypress');
        assert.equal($('#qunit-fixture').find('.has-error').is(':visible'), false);
      });

      $(document).ready(function () {
        $('#qunit-fixture').find('input').keypress(function() {
          $('.has-error').hide();
        });
      });

    </script>


Any thoughts? I'm sure it's not a bug and that I'm probably doing something dumb...

**Comment by vmanjunath** [comment]
Actually, you can ignore this. I was, indeed, being dumb. I just realized that the `#qunit-fixture` element gets replaced every time a new test is run so the bindings go away...

**Comment by leobalter** [comment]
:+1:
