### ISSUE TITLE
Set config from url

### ISSUE THREAD

**Issue by dtracers** [jquery/qunit#823]
for example

http://localhost:8080/myTest.html&autostart=false

I am trying to make a library to run tests and it would be very nice if this existed so that I can attach all of the event handlers before the tests run but after the page loads.

I also have no control over the source code only the url.

**Comment by leobalter** [comment]
the url params intend to support easy toggling features when they mean sense. `autostart` is not one of them.

I can't see a way you can't have control or access over the source code at all if you're running QUnit. This leaves a question: *how would you write your tests in this case?*

---

autostart is a feature that require control over the source code, without that, you can't even tell QUnit to start running. There's no good to add autostart as a urlparam.

**Comment by dtracers** [comment]
I feel like this could potentially be very useful especially for webdrivers.  Which is what I am currently using and why I asked this question.

And you could add a button that appears in the gui to let you start running the test if the autostart is off.


I have looked around it appears though that Intern accomplishes this and now uses the QUnit API so I think I will switch to that.

Thanks for the help.
