### ISSUE TITLE
Quoted "<" breaks diff oO

### ISSUE THREAD

**Issue by FagnerMartinsBrack** [jquery/qunit#824]
Using version 1.18.0: http://jsfiddle.net/yptmch4k/1/

When I compare the string `c=<` against `c="<"` using `strictEqual` the diff breaks, is it intended?

![image](https://cloud.githubusercontent.com/assets/835857/8020973/89b50a14-0c64-11e5-9294-88fac7257360.png)

**Comment by jzaefferer** [comment]
For the record, no, that's not intended. Looking for help to get this fixed.
