### ISSUE TITLE
QUnit.moduleStart invoked before each test

### ISSUE THREAD

**Issue by cezarypiatek** [jquery/qunit#825]
Hi
I have a problem with QUnit.moduleStart callback. It looks like this callback is invoked before each test not before module. I created a sample module with three tests and callback registered as below was fired three times
```javascript
QUnit.moduleStart(function (settings) {
    console.log("Module start");
});
```
I work with QUnit 1.18.0

**Comment by JamesMGreene** [comment]
Please provide your example code for the `module` and `test` calls as well so we can easily reproduce your exact scenario. Thanks!

**Comment by cezarypiatek** [comment]
Here is my sample with issue reproduction https://onedrive.live.com/redir?resid=419b0033f0b10f76!3319&authkey=!AO2MjOTaBdLZaxQ&ithint=file%2czip

The issue occurs when I load my test with delay (see IssueReproduction.js)

**Comment by jzaefferer** [comment]
When loading tests async you need to tell QUnit to wait, using `QUnit.config.autostart`. See the API docs for an example: http://api.qunitjs.com/QUnit.config/

**Comment by cezarypiatek** [comment]
It looks like I missed that parameter. Setting QUnit.config.autostart to false solved my problem. @jzaefferer  thank for your help.
