### ISSUE TITLE
Replace push(result, actual, expected, message, negative) with object signature

### ISSUE THREAD

**Issue by jzaefferer** [jquery/qunit#827]
As discussed in #822, the now even longer signature for `.push()` is bad. Especially with ES6 an object signature would work very well, `.push({ result, actual, expected, message, negative })`.

As I also mentioned in that PR: If we deprecate the current signature anyway, we might as well come up with a better name, since `push` is very generic. Any ideas for a better name?

**Comment by platinumazure** [comment]
Regarding a different name: How about something like `pushResult` or `addResult`? The information being added is a test assertion result, but `pushTestAssertionResult` seems a bit verbose.

Certainly open to other suggestions, of course.

**Comment by leobalter** [comment]
`pushResult` is interesting, as `resolve` would be a good inspiration from Promises.

**Comment by platinumazure** [comment]
Seems `resolve` might be confusing with promises and `assert.async` (just conceptually).

**Comment by gabrielschulhof** [comment]
How about just ```result()```?

**Comment by JamesMGreene** [comment]
Personally, I would say `assert`... but that will likely cause some confusion with extensions needing to call`this(...)` instead of `this.pushResult(...)`.

**Comment by jzaefferer** [comment]
Let's go with `.pushResult({ result, actual, expected, message, negative })`. The existing `push()` method can be updated to map to the newly added method.
