### ISSUE TITLE
jshint: test errors when running jshint task

### ISSUE THREAD

**Issue by iten123** [jquery/qunit#828]
I'm new here. When running "grunt", I encounter the following error: 
```
Running "jshint:all" (jshint) task

   Gruntfile.js
    141 |        browserSets = JSON.parse( browserSets );
                               ^ 'JSON' is not defined.
   dist/qunit.js
   1080 |        if ( !this instanceof Test ) {
                      ^ Confusing use of '!'.

>> 2 errors in 20 files
Warning: Task "jshint:all" failed. Use --force to continue.
```

Is it an error that damages the code or just a warning for coding quality?
I could modify .jshintrc to disable the JSON warning.
System: Mac OS X Yosemite

**Comment by mzgol** [comment]
I'm not getting these errors. Please remove the `node_modules` directory, invoke `npm install` and try again.

Also, on which commit are you trying?

**Comment by iten123** [comment]
I got the tar file from https://github.com/jquery/qunit/archive/1.18.0.tar.gz and then unzip it.
In the qunit-1.18.0 directory, I do:
```
npm install -g grunt-cli
npm install grunt
npm install ...(all the packages in 'devDependencies' in package.json)
```

and then still encounter this issue. 
Do I need to also remove node_modules in the root directory? Is there other dependencies I need to get?

**Comment by mzgol** [comment]
That's not the correct way to install dependencies. You should just invoke `npm install` without additional arguments, otherwise you're not installing proper versions. (but remove `node_modules` first).

BTW, this seems to be more a topic for support forums than this bug tracker.

**Comment by iten123** [comment]
Thanks, just invoke `npm install` solve the problem.
I should have realized to go through the forums first. Close it now.
