### ISSUE TITLE
How do we execute multiple test files with a single command?

### ISSUE THREAD

**Issue by nelsonic** [jquery/qunit#831]
## Scenario

We are trying to use the [**Node.js QUnit Module** aka _**qunitjs**_](https://www.npmjs.com/package/qunitjs) for our Server-Side Testing so that we can write one test and run it on both server and client e.g: https://github.com/nelsonic/learn-tdd/blob/master/test.js

When we run a single file using the command:

`node test/my_test.js`

It works as expected.

However, when we have more than one test in a [/**test**](https://github.com/nelsonic/hapi-socketio-redis-chat-example/tree/master/test) _directory_ and try to run all the files as a _suite_ using the following command:

`node test/*.js`

only the _first_ file (_alphabetically_) gets executed. 

see: https://github.com/nelsonic/hapi-socketio-redis-chat-example/tree/master/test
 
## Question

> _**How** do we **execute multiple test files** with a **single command**_?

We _tried_ to dig through existing StackOverflow + GitHub Q/A for this but did not find any match. (_any suggestions/help much appreciated!_)

## StackOverflow Points Up for Grabs!

> http://stackoverflow.com/questions/31312650/how-to-run-several-qunit-node-js-test-files-using-a-single-command

**Comment by jzaefferer** [comment]
How about a tiny wrapper script that passes your argument through (one of many) glob modules, then executes each file?

**Comment by JamesMGreene** [comment]
Or use existing wrappers like those available for Karma, Grunt, etc.

**Comment by nelsonic** [comment]
Thanks for your replies @jzaefferer && @JamesMGreene 
We were really hoping the node.js module would just read the /test directory out of the box the way Mocha or Tape do ... (_without having to use Grunt/Gulp etc_ ...)

Sounds like we might have to _write_ our own test runner that reads QUnit formatted files...
Does this kind of stand-alone project/node_module already exist to your knowledge?

**Comment by jzaefferer** [comment]
A few lines of globbing doesn't sound like much of a "test runner", but yes, its something QUnit itself (`qunitjs` on npm) doesn't do, yet. You could also try the [qunit module on npm](https://www.npmjs.com/package/qunit), which provides more node-specific options.

**Comment by nelsonic** [comment]
I'm not entirely happy with the way `node-qunit` runs test.
but the output is pretty decent.

Usage:
```sh
 ./node_modules/qunit/bin/cli.js -c ./lib/*.js -t ./test/*.js
```
<img width="843" alt="run-qunit-cli" src="https://cloud.githubusercontent.com/assets/194400/8676918/2dcccc2a-2a44-11e5-9929-86268e6791a6.png">

example: https://github.com/nelsonic/try-node-qunit
