### ISSUE TITLE
Extend assert.async to accept a count of asynchronous operations

### ISSUE THREAD

**Issue by gibson042** [jquery/qunit#843]
Currently, `assert.async` returns an invoke-once callback, which can lead to overly-cumbersome patterns (e.g., [manual counter tracking](https://github.com/jquery/jquery/blob/acda1d633fd6c8a0a7dc8b8236780daa3fe44cc1/test/unit/basic.js#L9-L22) or [collect and pop](https://github.com/jquery/jquery/blob/1c59b308d201d6dd0f0aed2ad0256d01b9f68047/test/unit/deferred.js#L411-L421)). It would be more convenient to specify the expected count of invocations explicitly by argument:
```js
var done = assert.async( 4 );

asyncOperation1( function( result ) {
	assert.equal(…);
	done();
} );
asyncOperation2( function( result ) {
	assert.equal(…);
	done();
} );
…
```

**Comment by mzgol** [comment]
This would be great and seems a common enough pattern.

**Comment by mixed** [comment]
+1 for this feature.
@jzaefferer Could I work on this issue?
