### ISSUE TITLE
Generate a failure when QUnit.start is passed a non-numeric argument

### ISSUE THREAD

**Issue by gibson042** [jquery/qunit#846]
Ref #844

When `QUnit.start` is passed a truthy but non-numeric argument, its [test semaphore decrement](https://github.com/jquery/qunit/blob/d47da30d950ba4b1496e70879eb583e982cbb440/src/core.js#L76) sets `config.current.semaphore` to `NaN`. Such a condition should generate output analogous to the "Called start() while already started…" failure presented when `semaphore` dips below zero.

**Comment by platinumazure** [comment]
I'd love to submit a pull request, but I'm not sure what the best way to handle this situation is. I suppose throwing an exception for an invalid value would make sense, but is there a better way?

**Comment by leobalter** [comment]
@platinumazure 

You should probably use `QUnit.pushFailure` with a message argument. Ref: https://github.com/jquery/qunit/blob/master/src/test.js#L297

**Comment by jzaefferer** [comment]
@platinumazure is this still something you want to work on?

**Comment by platinumazure** [comment]
Ack, sorry, I've been busy with a bunch of other things. If anyone wants to jump on this now feel free.

**Comment by rdugue** [comment]
Hello, I would like to make a pull request if possible.  Should `config.current.semaphore` be set to a specific value in this case?

**Comment by gibson042** [comment]
Given that it's already a configuration failure, I don't think the value matters much. But I suppose `0` would let us just get on with the rest of the suite.
