### ISSUE TITLE
Safari 7.0 isn't tested

### ISSUE THREAD

**Issue by mzgol** [jquery/qunit#855]
BrowserStack has removed Safari 7.0 from the API, I notified them that it's a problem for us. However, because of [these lines of browserstack-all.json](https://github.com/jquery/qunit/blob/master/browserstack-all.json#L21-L22) you now wouldn't even try to this version; only Safari 5.1, 6.2, 8.0 & 9.0 are included. This means Safari 6.0 & 7.0 is gone (6.2 has an identical engine as 8.0).

Due to the fact of how messed up Safari versioning is:

1. Safari 8.0, 7.1 & 6.2 share the WebKit version
2. Safari 7.0 & 6.1 share the WebKit version

I think it's dangerous to just rely on aliases; it'd be better to explicitly list all Safari versions supported; and do it without shortcuts like `safari_6` but use the full `safari_6_0` name.

**Comment by leobalter** [comment]
Thanks for letting me know.

Does safari_6_2 works? otherwise we'll need to specify each browser without aliases.

**Comment by mzgol** [comment]
I'm not sure but you specify `safari_5_1` already so I assume it should. It's best to include every Safari version since `6.0` with the `_0` suffix as minor updates are basically the same as major ones in this land.

**Comment by leobalter** [comment]
I'll have to test it, browserstack does not document the aliases and some key names does not work.

**Comment by jzaefferer** [comment]
Btw. Safari 7 is back in the API (I think), apparently it won't come back in Live though, so don't expect to see it there.

**Comment by mzgol** [comment]
Yup, I've restored it for projects using TestSwarm.

**Comment by mzgol** [comment]
Please see https://github.com/jquery/jquery/issues/2609. It seems the new Safari 7.0 is a fake one and under the hood it has a 7.1/8.0 engine so don't rely on its results for now. :/ I notified BrowserStack about the issue.

**Comment by jzaefferer** [comment]
Core is not going to test against Safari 7.0 anymore, so we don't have to bother either.
