### ISSUE TITLE
Automated migration tools for QUnit 2.0 syntax

### ISSUE THREAD

**Issue by platinumazure** [jquery/qunit#868]
Hi folks,

I've been working (occasionally) on a QUnit migrator tool, [platinumazure/qunit2-migrator][1]. Today I learned of another tool being developed, [apsdehal/qunit-migrate][2].

Before I get too much further, I'd like to confirm with the QUnit team: Are there any plans to create or support a migration tool? If so, what do I need to do to either win support for what I have done or to gracefully fold in my tool's capabilities to whatever the "official" migration tool may be? And if there are no plans to support a tool, what is the best way for me to request extra eyes on it and get feedback without spamming people?

  [1]: https://github.com/platinumazure/qunit2-migrator
  [2]: https://github.com/apsdehal/qunit-migrate

**Comment by jzaefferer** [comment]
As a quick note: We should add links on both the plugins and the upgrade guide pages to available migration tools. 

I'll get back to the actual question later.

**Comment by jzaefferer** [comment]
It looks like your tool is based on AST transforms, while @apsdehal's tool is using regex. He mentioned (https://github.com/apsdehal/qunit-migrate/issues/4#issuecomment-145562918) that he'd like to switch to using JS AST, so that seems like a good opportunity to collaborate. It would be great to have one really solid tool instead of two that mostly solve the same problem.

@apsdehal since you mentioned moving to AST, would you consider contributing to @platinumazure's tool?

**Comment by apsdehal** [comment]
@jzaefferer I can contribute to @platinumazure's tool, but the tool I developed came into existence mostly because of the custom needs of jquery-projects and the custom syntax. Thus I further modified it to a more general support. I can't immediately halt the development on it until @platinumazure's tool take care of different syntax, good wikis and a few other stuff. We can work together in that direction.

**Comment by platinumazure** [comment]
@apsdehal The syntax tree transformation I selected, [recast](https://github.com/benjamn/recast), was chosen specifically to try to preserve existing syntax and spacing and things, although it does have a few bugs when new statements are generated. Could you please either provide me some test cases using jQuery or other custom syntax, or try running the tool against said syntax, and open issues (or otherwise let me know) for any problems that show up? Thanks!

**Comment by apsdehal** [comment]
@platinumazure You can select data number 8, 9 and 10 from https://github.com/apsdehal/qunit-migrate/tree/master/tests/data. These all have been taken from jquery projects.

**Comment by platinumazure** [comment]
Understood. I'll give it a try in the next couple of days.

**Comment by leobalter** [comment]
It is great to see how this is going. Ping me if you need any help.

**Comment by jzaefferer** [comment]
How about we add links to both tools (while they're not merged, or whatever will happen) to the plugins page and the top of the migration guide? With those in place we can close this ticket, then update the links later as things progress.

**Comment by platinumazure** [comment]
@jzaefferer :+1:

@apsdehal Sorry for not getting back to you-- I've been incredibly busy at work. I'm hoping to try my tool out on your test cases this week.

**Comment by jzaefferer** [comment]
@apsdehal @platinumazure was there any progress towards merging these tools?

**Comment by platinumazure** [comment]
No, and I've stopped working on my tool. @apsdehal has made good progress
on his tool. It can be the "official" one, if everyone agrees it is up to
snuff.

Sorry, I just don't have the bandwidth to maintain my migration tool on top
of my other projects right now :cry:
On Apr 20, 2016 4:40 PM, "Jörn Zaefferer" <notifications@github.com> wrote:

@apsdehal <https://github.com/apsdehal> @platinumazure
<https://github.com/platinumazure> was there any progress towards merging
these tools?

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/jquery/qunit/issues/868#issuecomment-212618322>

**Comment by jzaefferer** [comment]
Alright, thanks for letting us know. 

I lost track of the previous discussion (and I'm not sure what might still be relevant). Seems like @apsdehal could maybe add your test cases to this project. Either way, we should link to it in the migration guide.

**Comment by jzaefferer** [comment]
See https://github.com/jquery/qunitjs.com/issues/120 for adding the note to the migration guide.
