### ISSUE TITLE
QUnit Tips and Tricks on Global Ember Meetup

### ISSUE THREAD

**Issue by taras** [jquery/qunit#892]
EmberCLI uses QUnit as it's default test runner. Most people in Ember community use it on daily bases, but there are probably more advanced techniques that they're not familiar with. 

Would someone who knows QUnit well be interested in giving a lightning talk on "QUnit Tips and Tricks" at next [Global Ember Meetup](http://global-ember-meetup.com) in 2 weeks?

**Comment by leobalter** [comment]
That's cool, but I'm afraid there's not a lot of unknown tricks on QUnit, but you might be interested to know on the QUnit roadmap and it is affected by Ember, not only on the development of features, but with a similar release process.

**Comment by leobalter** [comment]
@gibson042, @jzaefferer are you interested? Otherwise I'm in. :)

Thanks for the invite, @taras!

**Comment by gibson042** [comment]
I think you're it, @leobalter!

**Comment by taras** [comment]
> QUnit roadmap and it is affected by Ember

I agree, people would find this very interesting. 

Would you be able to prepare something for November 21st? 

Here is a link to the event https://www.bigmarker.com/global-ember-meetup/Ember-Testing-Day

**Comment by leobalter** [comment]
Sure! It is very exciting to share the experience with Ember community! I'm looking forward!

**Comment by taras** [comment]
Awesome, I’ll add you to the list.

-- 
Taras Mankovski

On November 16, 2015 at 11:27:49 AM, Leo Balter (notifications@github.com) wrote:

Sure! It is very exciting to share the experience with Ember community! I'm looking forward!
