### ISSUE TITLE
hidepassed needs to check for the right element

### ISSUE THREAD

**Issue by jzaefferer** [jquery/qunit#896]
From #819:

---

Just got around to looking into this. The problem above can be reproduced by removing the element with id `qunit`.

Basically, we wanted to have our own header, so we had manually added the following HTML to the page:

```html
   <!--
    <div id="qunit"></div>
   -->
    <h1 id="qunit-header">
          // Custom header here
    </h1>
    <div id="qunit-testrunner-toolbar"></div>
    <ol id="qunit-tests"></ol>
```

This actually works, except that `hidepass` is not honoured.

The problem code is the following in `QUnit.begin`

```JavaScript

	if ( qunit && config.hidepassed ) {
		addClass( qunit.lastChild, "hidepass" );
	}

```

This code is inconsistent, because the `hidepass` is actually in `qunit-testrunner-toolbar` and existence of that element should imply that the code runs correctly. Probably

```
	addClass( qunitToolbar.parentElement.lastChild, "hidepass" );
```

**Comment by leobalter** [comment]
good catch. I'll see if I can fix it soon.
