### ISSUE TITLE
notOk assertion has wrong label

### ISSUE THREAD

**Issue by mrjohn0011** [jquery/qunit#899]
1. Write test with assert.notOk(true);
2. Run test and see expected: "NOT false", but really expected is "NOT true"

In the following example, $item has css-class "dx-state-focused", so, expression is TRUE, but the label is "NOT false"

![uf4uqnr](https://cloud.githubusercontent.com/assets/16186141/11621628/34a5f762-9ccf-11e5-9b1e-59c831a8215f.png)

**Comment by leobalter** [comment]
Confirmed.

As `assert.ok` says `expected: true`, `.notOk` should express a `NOT true` or `false`.

**Comment by JamesMGreene** [comment]
Technically, they should probably say `NOT truthy` and `NOT falsy`.

**Comment by leobalter** [comment]
> Technically, they should probably say NOT truthy and NOT falsy.

It would be a ++ to solve it this way. 

I am linking this issue to some friends as a "Good first PR".

**Comment by leobalter** [comment]
> Technically, they should probably say NOT truthy and NOT falsy.

re-reading this:

assert.ok => the default *expected* value should be a `truthy`, or `true`
assert.notOk => the default *expected* value should be a `falsy`, 'not truthy', or `false`

These values are for the Expected parameter used for diff purposes, not the result message.

**Comment by JamesMGreene** [comment]
Right-o, @leobalter.

**Comment by MMD-Coding** [comment]
Hey, finally found an issue to submit for 24pullrequests :smile: Thanks for letting it open.

I would like to fix it, but I'm not really sure if I just replace the `expected` argument with a string. If I do so it looks a bit weird because it adds quotes to the "Expected: ..." output. I would propose just to remove the `negative` argument on `assert.notOk` and leave the rest. What do you think?

**Comment by leobalter** [comment]
the negative assertions are prefixed with a "NOT" label on the HTML Reporter, the expected value is `false` (or equivalent) on `.notOk`. 

the label prefix on negative assertions makes sense to every other assertions as notEqual, notStrictEqual, notDeepEqual, etc, but it shouldn't be applied to `notOk`.
