### ISSUE TITLE
Regex test filtering

### ISSUE THREAD

**Issue by trentmwillis** [jquery/qunit#904]
Would it be possible to introduce regex test filtering? There are cases where we want a subset of our test suite to run but can't achieve it with a simple string filter. Maybe my thinking is naive, but it seems like we should be able to take the filter string and cast it to a regular expression and test the test names against it.

This would probably require an additional config option to treat the filter as a regular expression as opposed to a string value.

**Comment by leobalter** [comment]
This is a good question and I would like to discuss before making a decision.

I currently have some limited filters as filtering by the test names, the module filters and using `QUnit.only` for single test blocks.

It does not look like a problem to cast the filter string to a regular expression.

QUnit.pending (not implemented yet) would be helpful here but it targets a different strategy.

**Comment by leobalter** [comment]
The config option might be too much, we should try casting the filter string as a regular expression without any option to enable or disable it, the option would be an unnecessary complexity.

**Comment by gibson042** [comment]
Using the existing parameter is fine by me, but we'll need some in-band method of differentiating string matches from regex patterns (similar to the preexisting [leading `!` for filter inversion](https://github.com/jquery/qunit/blob/efe03030a6f22ff002de8ee6164b74af74018254/src/test.js#L392-L395)) so regex-special characters can still be matched literally. E.g., something like `filter=/regexp?/i` (optional "p") vs. `filter=regexp?` (literal "?").

**Comment by leobalter** [comment]
seems right.

We may also trigger the regexp match if the filter value matches a valid regexp literal notation (using the `/content/params?`

I'm interested to see how it might be implemented. @trentmwillis would you like to try a PR with it?

**Comment by trentmwillis** [comment]
These cases are actually why I thought an additional config option might be valuable as it takes some of the guess work out of determining what sort of pattern we're using. For example, what I'm seeing with the above is:

`/components/g` -> Does a global regex search for `components`
`/components/s` -> Does a regex search for `/components/s`?

I think trying to determine if we should be treating values as regex patterns or literals would add uncertainty to the end user.

**Comment by gibson042** [comment]
The mechanism doesn't matter to me, as long as behavior is predictable and we maintain backwards compatibility with respect to non-initial special characters.

**Comment by trentmwillis** [comment]
Did an implementation that added an additional config option. @leobalter if you feel strongly that we should not add another config option, I can explore other alternatives.

**Comment by jzaefferer** [comment]
Btw. I feel strongly that we should not add another config option.

**Comment by trentmwillis** [comment]
Noted, will attempt the other approach and update my PR.
