### ISSUE TITLE
Regular expression comparison ignores ES2015 "unicode" flag

### ISSUE THREAD

**Issue by gibson042** [jquery/qunit#909]
e.g., `/\u{1D306}/u.flags === "u"`.

Using the new [`flags` property](http://www.ecma-international.org/ecma-262/6.0/#sec-get-regexp.prototype.flags) in [`equiv`:`callbacks["regex"]`](https://github.com/jquery/qunit/blob/41322e7a8f521096859cc9c767df088797ed0608/src/equiv.js#L82-L88) should future-proof us against all future additions.

**Comment by leobalter** [comment]
and it seems like a easy one to fix. 

@mixed, would you like to help fixing this?

**Comment by mixed** [comment]
@leobalter 
OK. I have fixed it. :smirk:
