### ISSUE TITLE
Request: deepContains

### ISSUE THREAD

**Issue by mmun** [jquery/qunit#911]
I'm not sure what the policy on adding new assertion helpers is but I figured I'd make an issue anyways. 

I've often wanted an assertion similar to `deepEqual` but that only checks equality on the values specified in the on the "expected" side. Example,

```js
let obj = {
  a: 1,
  b: { x: 2, y: 3 }
};

assert.deepContains(obj, { b: { x: 2 } }); // pass
assert.deepContains(obj, { a: 1, b: { x: 2 } }); // pass
assert.deepContains(obj, { a: 2, b: { x: 2 } }); // fail
```

The name is up for bikeshedding.

**Comment by leobalter** [comment]
This seems interesting but currently it seems better to be included as an Assert plugin, not directly on the core api.

@jzaefferer, thoughts?

**Comment by JamesMGreene** [comment]
Definitely better off in a plugin, IMHO.

**Comment by mmun** [comment]
Is there a way to write a plugin like this that reuses code from the deepEqual implementation? It's important that they have the same equality semantics.

**Comment by jzaefferer** [comment]
In #865 we discussed/planned to replace our implementation with the one from lodash. If that goes through, you could build the plugin on top of the same implementation.

**Comment by mmun** [comment]
Great! :)

**Comment by leobalter** [comment]
Regardless the solution we find on #865, the idea is to expose it on `QUnit.equiv`. So you can start building a plugin on top of this method.

**Comment by JamesMGreene** [comment]
If you happen to be using this for Node.js, I'd recommend just using the ["lodash.ismatch"](https://www.npmjs.com/package/lodash.ismatch) sub-module (equivalent to [`_.isMatch`](https://lodash.com/docs#isMatch)) in a custom assertion, e.g.

```js
var isMatch = require('lodash.ismatch');
QUnit.assert.matches = function( actual, expected, message ) {
  (this.push || QUnit.push)( isMatch( actual, expected ), actual, expected, message || 'Actual does not match expected' );
};
