### ISSUE TITLE
QUnit.equiv treats Map and Set as ordered

### ISSUE THREAD

**Issue by gibson042** [jquery/qunit#915]
https://jsfiddle.net/xd2jnbLa/

I think we should ignore insertion order when comparing these objects ~~(along with WeakMap and WeakSet, which we ignore completely)~~.

**Comment by leobalter** [comment]
There is no way to discover the collections on WeekMaps and WeakSets, that's why it's ignored and compared as regular objects.

> we should ignore insertion order

+1 to this.
