### ISSUE TITLE
`jscs task` normally doesn`t working.

### ISSUE THREAD

**Issue by mixed** [jquery/qunit#917]
`jscs task` doesn't normally working because `grunt-jscs` version is low. `jscs task` is normally working when  `grunt-jscs` version up.

Ref #916

**Comment by leobalter** [comment]
we need to update our grunt jscs and jshint tasks.

This is a duplicate of #879.

@mixed, would you like to help on this one as well? It's more than just updating the packages, but also fixing some code styles.

**Comment by mixed** [comment]
@leobalter 
Ah.. OK.
If @arghgr don't mind it I can it. package update, fixing some code styles.
