### ISSUE TITLE
reordered test runs issue

### ISSUE THREAD

**Issue by jdalton** [jquery/qunit#927]
I've run into an issue with Ember's unit tests when they upgraded from QUnit 1.18.0 to 1.20.0 with retrying tests. Before the rather long url of 

*tests/index.html?testId=3cc72180&testId=76cb477a&testId=78ef0a1c&testId=d0487dc9&testId=1d54b55d&testId=db4d08bd&testId=ad7f8de5&testId=dd527213&testId=17371bf6&testId=5ee3df71&testId=d5a89651&testId=9a1a7024&testId=a85bac39&testId=7058f532&testId=1de16bf5&testId=ccce39f2&testId=926434d2&testId=b78ea630&testId=cb041f6b&testId=0a58ebc7&testId=c7660ba0&testId=8507e759&testId=6e6efbd0&testId=039fcabf&testId=41cdaf57&testId=28537e92&testId=18a7bd54&testId=6f7a34a1&testId=5aa846fd&testId=12a6c98b&testId=2c07193f&testId=19da7e96&testId=fb2d4548&testId=8e6efed2&testId=d3b0ade2&testId=f05b6bb0&testId=6ff38b82&testId=9f97cbc1&testId=30b3451c&testId=927999ec&testId=bcb65df7&testId=570c2caa&testId=5cd3ee89&testId=614f1561&testId=67d305eb&testId=02ee93e6&testId=b6fa00d8&testId=dbd0c265&testId=4e551122&testId=88552927&testId=b08ce9d2&testId=5ba83754&testId=90f74ea1&testId=5df0b653&testId=dc46afe8&testId=95cf50f8&testId=8e049e95&testId=7325b082&testId=fc68b2a8&testId=55c9508e&testId=507fe8d2&testId=eefe2476&testId=2687e733&testId=59bf32d5&testId=c26a825d&testId=c06d6198&testId=b8b60f68&testId=26db00de&testId=f877a233&testId=d4b8b77e&testId=ce28bd57&testId=0237bd38&testId=407e1559&testId=526facce&testId=bee41d59&testId=e182cd63&testId=f9bba72c&testId=28ac8a43&testId=649b3e40*

with 79 test ids would work. But now on refresh it only runs 39 of them. If I run it in a new tab it runs all 79 which makes me think it's a `sessionStorage` and `reorder` issue. May be related to something around https://github.com/jquery/qunit/compare/1.18.0...1.20.0#diff-f6c2ded91c9881cdc31b5bfcabb54c3bR267. I'm working to get confirmation that it is `reorder`.

**Comment by leobalter** [comment]
haha. This is such an interesting issue while at the same time I'm expressing a big WTF checking this link.

@jdalton++

I'm not sure where to start here, but it's gonna be worth investigating. Probably a `git bisect` will help to find the source.

**Comment by JamesMGreene** [comment]
Not sure if there is any hidden relationship but when I received the notification email from GitHub of @jdalton's comment, one of the ampersands came through as `&amp;` (or maybe `&amp ;`?) while rest were just `&`... looks approximately halfway through the list... maybe after 39?

```
&testId=bcb65df7&amp ;testId=570c2caa&
```

**Comment by jdalton** [comment]
The `QUnit.urlParams` object is still populated with 79 entries when only 39 are run.

**Comment by JamesMGreene** [comment]
OK, just a random email fluke then. :+1:

**Comment by jdalton** [comment]
Fixed in 1.21.0 by
> Test: Prevents skiping tests after rerun reordering

**Comment by leobalter** [comment]
@gibson042 and @mixed++, they worked on that fix.

**Comment by jdalton** [comment]
![](https://cloud.githubusercontent.com/assets/4303/12901983/4200f512-ce73-11e5-82b8-11eca32a03cd.gif)
