### ISSUE TITLE
Suggest to fixture method.

### ISSUE THREAD

**Issue by mixed** [jquery/qunit#929]
If I have to use fixture It has some ways.
## 1. Add html in `#fixture`.
```html
<div id="fixture">
	<span>1</span>
</div>
```
This case has some cons. `fixture` is too hard to read and maintain If I have many fixture. For example. It can't know `fixture` in [testcase](https://github.com/naver/egjs/blob/5dc0a716bdd6e4c78d7cb1e8dc7d566e1ca0febd/test/js/flicking.test.js#L96-L100). So. I search for `#fixture` in [html](https://github.com/naver/egjs/blob/5dc0a716bdd6e4c78d7cb1e8dc7d566e1ca0febd/test/flicking.test.html#L25-L90) but It is hard to search.

## 2. Append html using `append` or ....
```js
jQuery("<span>1</span>").appendTo("#fixture");
```
This case has resolve uppon problem. but I feel like a hack.

### Add method
`QUnit.fixture`
- set html
- return childnodes of `#fixture`
```js
// pseudo code
QUnit.fixture = function( html ){
	document.getElementById("fixture").innerHTML = html;
	return document.getElementById("fixture").childNodes;
}
```
```js
QUnit.test( "fixture example1", function( assert ) {
	QUnit.fixture("<span>1</span>");
	assert.ok( true, "this test is fine" );
});

QUnit.test( "fixture example2", function( assert ) {
	// return childeNodes of #fixture
	var childeNodes = QUnit.fixture("<span>1</span>"); 
	assert.equal( childenodes.length, 1 );
});
```

### make #fixture in js.
When I use `fixture` I have to add `#fixture` in html.  If `Qunit` make `#fixture` in js when it hasn't `#fixture` I can use easy `fixture`.

**Comment by leobalter** [comment]
@mixed, the proposal is interesting and it seems good enough to run without the need to access any internal from QUnit.

With that said, I believe this would be better published as another module/package, like `qunit-fixture` on npm.

**Comment by mixed** [comment]
@leobalter 
Thank you. I have published a [qunit-fixture](https://github.com/mixed/qunit-fixture).

**Comment by leobalter** [comment]
That's great! You may add it to the plugins page at qunitjs.com
