### ISSUE TITLE
Copy deepStrictEqual and notDeepStrictEqual from node.

### ISSUE THREAD

**Issue by kellyselden** [jquery/qunit#930]
I currently polyfill these in my browser tests. It would be great if QUnit shared these functions. Added [here](https://github.com/nodejs/node/pull/639).

**Comment by kellyselden** [comment]
After looking through the code, it looks like the deep functions are using strict. Interesting...

**Comment by leobalter** [comment]
:+1: 

We also have plans to replace the internal implementation of deepEqual, potentially using LoDash's isEqual: #865
