### ISSUE TITLE
Tests: Define setup and tests near each other

### ISSUE THREAD

**Issue by gibson042** [jquery/qunit#934]
Cf. https://github.com/jquery/qunit/pull/931/files#r53812901

Some of our tests ([logs](https://github.com/jquery/qunit/blob/e97213599c87a505d599386b4b98e25d4b5ee14d/test/logs.html), [regex-filter](https://github.com/jquery/qunit/blob/e97213599c87a505d599386b4b98e25d4b5ee14d/test/regex-filter.html), etc.) utilize what I consider to be a suboptimal pattern:

**test/example.html**
```html
<script>
	QUnit.config.property = value;
</script>
<script src="example.js"></script>
```

**test/example.js**
```js
QUnit.module(…);

QUnit.test(…);
…
```

I'd like to see the setup and tests defined together.

**Comment by trentmwillis** [comment]
:+1: seems good to me. I feel like this was probably done once and then just followed as a pattern. I don't see much reason not to merge setup and tests.
