### ISSUE TITLE
Leverage semver for devDependencies

### ISSUE THREAD

**Issue by trentmwillis** [jquery/qunit#937]
As I was working on #879, I was wondering if we should consider switching our `devDependencies` to leverage semver rather than pegging explicit version numbers for everything. Taking a look at [David DM shows almost all our dependencies are out of date](https://david-dm.org/jquery/qunit#info=devDependencies&view=list), we could mitigate this by using either `^` or `~` for our dependency versions.

**Comment by mgol** [comment]
Most of jQuery repos went in the opposite direction. Semver is an idea but reality is that from time to time a package breaks and then we have a problem. IMO it's better to just pin versions and update from time to time. Note that using non-latest version of a dependency isn't a bad thing; maybe they introduced a new feature we don't use, maybe a bug fix that doesn't affect us that much. It's good to not lock down to something ancient but it doesn't mean constantly living on the bleeding edge is an adequate answer either.

**Comment by trentmwillis** [comment]
Okay, if that's the direction the larger jQuery org has gone then I'm fine with it. I'm definitely familiar with the issues you describe, but on the flip side I also enjoy staying up-to-date to gain passive benefits (e.g., performance and bug fixes) and when things do break it gives you an opportunity to contribute back to your dependencies. Just thought I'd bring it up for discussion.

**Comment by leobalter** [comment]
The current devDependencies work for what we need and locking their respective versions help us to reproduce the same results anywhere. This approach avoid regressions or releases that won't follow semver.

In another perspective, this project needs more updates on the npm packages, avoiding a lock down on ancient modules.

**Comment by trentmwillis** [comment]
Marking this as closed, but glad we now have some public documentation for our approach here.
