### ISSUE TITLE
Add warning if `!details.result` and `actual === expected` for unknown reason.

### ISSUE THREAD

**Issue by Parakleta** [jquery/qunit#938]
In [reporter/html.js#L674-L713](https://github.com/jquery/qunit/blob/65706a1cef576d008b2a714a21cc98a37cf54f29/reporter/html.js#L674-L713) if the test has failed a decision is made about what to actually report.

Prior to 87061fb82bcf9a248c56ccf235b164e989ae2935 the check that `actual != expected` was required to suppress printing the `actual` and difference since there was no `if (!result)` test.  After that change the `actual != expected` test only served to suppress the diff calculation when there would be no diff.  Now (as of ecc33ac75eda91bbe8f31349211325a127bfb913) the `else` clause of that test is also used together with the check that `expected` contains an unexplored array or object to warn that the `QUnit.dump.parse()` has insufficient `QUnit.dump.maxDepth` to express a difference between the objects.

I'd like to propose that a general warning be added as an additional `else` clause to catch all other cases where the test has failed but the `QUnit.dump.parse()` couldn't detect the difference.  The absence of any mention of the `actual` value in some failing tests has recently caused me some confusion because I couldn't tell if the lack of reporting was a bug in QUnit or a problem with my tests. It turned out in this case (obviously in hindsight) that `deepEqual` was needed to compare `NaN`, but other causes of failure could be differing document objects or functions.

**Comment by trentmwillis** [comment]
@Parakleta I'm having a bit of trouble groking what the precise issue you're describing is. Can you provide a reproduction jsfiddle or something similar? Or, at least, what you feel this warning should say?

**Comment by Parakleta** [comment]
This [fiddle](https://jsfiddle.net/parakleta/37s44y1n/) shows three cases where the test fails but the `expected` and `actual` appear the same according to `QUnit.dump.parse()` and so there is no reporting of why the test failed.  I think I'd just like if there was some message such as for the `maxDepth` case, something like:

"Message: Diff suppressed as the expected and actual results have an equivalent serialization"

**Comment by trentmwillis** [comment]
Okay, thanks a lot for the examples! This seems like a reasonable ask, would you mind submitting a PR for it? We might work the exact wording of the error a bit, but I like the idea.
