### ISSUE TITLE
Development is broken on Windows 10 environment

### ISSUE THREAD

**Issue by leobalter** [jquery/qunit#940]
The current development is broken on Windows 10 environment.

There are more than one breaking point. The first is on grunt-contrib-concat, where it concat files with the Windows EOL character. JSCS throws a code style error.

```
λ grunt jscs
Running "jscs:all" (jscs) task
Invalid line break at dist/qunit.js :
    11 |
    12 |( function( global ) {
    13 |
--------^
    14 |var QUnit = {};
    15 |
>> 1 code style errors found!
Warning: Task "jscs:all" failed. Use --force to continue.
``` 

The other error is due to the test-on-node tests on QUnit.stack (`test/main/stack`), where it fails at `QUnit.stack: returns the proper stack line`.

I did a clean install of npm packages both on my original environment and windows environment. Both are using Node 5.7.0 and npm 3.6.0.

I need to investigate this further.

**Comment by leobalter** [comment]
As @trentmwillis suggested at #936, it's interesting to use a windows based CI to avoid this in the future.

**Comment by trentmwillis** [comment]
Bah, auto-closed but there is still one more fix that needs to go in, so reopening.

**Comment by trentmwillis** [comment]
Fixes have been pushed. Should we use this issue or open a new one to track the possibility of using a Windows-based CI?

**Comment by leobalter** [comment]
It's better if we keep track of it on another issue (#943), as it is not critical or urgent as the others already addressed here.

Thanks!
