### ISSUE TITLE
Use a windows based CI

### ISSUE THREAD

**Issue by leobalter** [jquery/qunit#943]
Ref #940

cc @trentmwillis

**Comment by trentmwillis** [comment]
A quick search for ["windows ci"](https://www.google.com/#q=windows+ci), doesn't yield a lot of promising results. I'm familiar with using [AppVeyor](https://www.appveyor.com/) and know that the Ember-CLI project also uses it. It is also quite similar to Travis and is easy to set up, so this may be the best option unless anyone has another recommendation.

**Comment by leobalter** [comment]
I am ++ to use AppVeyor.

**Comment by trentmwillis** [comment]
I'll look into setting it up sometime soon. What scripts should we run? I'm thinking we can just do `npm test`, I don't see much reason to run coveralls and browserstack in both CIs.

**Comment by leobalter** [comment]
npm test is the one we should care about.
