### ISSUE TITLE
Suggestion [HTMLReporter]: make it possible to pass comma separated modules to `module` param

### ISSUE THREAD

**Issue by Arkni** [jquery/qunit#951]
Hi all,

I wonder if it's possible to specify a comma separated names, instead of specifying one module to run, like so:
```
http://localhost:8000?module=module1,module2
```

or
```
http://localhost:8000?module=module1&module=module2
```

Thanks :)

**Comment by trentmwillis** [comment]
You could accomplish this using the recently introduced [regex filtering](https://github.com/jquery/qunit/commit/e97213599c87a505d599386b4b98e25d4b5ee14d):

```
http://localhost:8000?filter=/module1|module2/
```

We should probably add documentation for that feature...will try to do that this week.

**Comment by Arkni** [comment]
Please correct me if I'm wrong.
So if I'm using a filter like: `filter=core`, this will run all the tests that are under the module `core`, or also the tests that have `core` in the name.

From the commit you linked, this only available starting from `v1.21.0`.

> We should probably add documentation for that feature...will try to do that this week.

I appreciate that :)

**Comment by Arkni** [comment]
Also, the config option `moduleFilter` doesn't seem to work in latest releases.
**Simple code:**
```js
// Only the module `module1` should run, unfortunately doesn't work
QUnit.config.moduleFilter = "module1";
QUnit.module( "module1" );
QUnit.test( "test11", function( assert ) {
	assert.ok( true );
} );
QUnit.test( "test12", function( assert ) {
	assert.ok( true );
} );
QUnit.module( "module2" );
QUnit.test( "test21", function( assert ) {
	assert.ok( true );
} );
QUnit.test( "test22", function( assert ) {
	assert.ok( true );
} );
```

**JSfiddle:** https://jsfiddle.net/Arkni/tg6pzL4a/

**Comment by Arkni** [comment]
I tested the `filter` option , even though it's not what I'm after. But I can live with that.
Feel free to close this issue if you see it as resolved. But please notice the issue I mentioned in my previous comment (https://github.com/jquery/qunit/issues/951#issuecomment-194515024).

**Comment by trentmwillis** [comment]
@leobalter can you give more insight into removing `config.moduleFilter`? Seems like it was intentional. If so, we should update docs. Also, how would someone now programmatically set the module filter?

@Arkni I can understand your desire for a multi-module filter. I think the primary concern I have is introducing too many ways for users to filter their tests. Additionally, the current module filter is tied to a drop-down, how would we represent multiple modules in that sort of UI?

**Comment by Arkni** [comment]
> I think the primary concern I have is introducing too many ways for users to filter their tests

Thank you for your effort :)

> Additionally, the current module filter is tied to a drop-down, how would we represent multiple modules in that sort of UI?

I thought of that too. One solution would be styling the multiple select or replace it with a list of checkboxs the same way done in [`bootstrap-multiselect`](http://davidstutz.github.io/bootstrap-multiselect/) or a list of tags like in [`Select2`](https://select2.github.io/examples.html), for example. But this requires some additional work just to make it functional.

I guess it should be left as is.

**Comment by Arkni** [comment]
OK, after evaluating #952, here is what I came up with:
* If not possible for a user to know the hash of a module name, then what's the benefit for the user to use that config, I mean programmatically without interacting with the HTML reporter.
* As a solution of the first point, you can export the hashing method as utility, so the user can use it to hash the module names that he want to run.

@trentmwillis what do you think ?

**Comment by trentmwillis** [comment]
From that same PR:

> We should progress this feature to a UI change for sure. I'm ok if we have it documented on the api page and follow up the missing parts on another PR. - @leobalter 

So the intention is that we will have some UI changes that will expose the `moduleId` in some way, it'll just be added in a further iteration. Given my earlier question ("how would we represent multiple modules in that sort of UI?"), I imagine this will have some discussion around it, so I will open a separate issue to track that feature.

**Comment by Arkni** [comment]
> So the intention is that we will have some UI changes that will expose the moduleId in some way, it'll just be added in a further iteration.

Thanks for pointing that :)

**Comment by leobalter** [comment]
> can you give more insight into removing config.moduleFilter? Seems like it was intentional. If so, we should update docs. Also, how would someone now programmatically set the module filter?

I need to check on the history to give you the right answer.

>  I will open a separate issue to track that feature.

++ for that. It's not simple or easy to say how it's gonna be. The new issue will help us discussing the best way to do it.
