### ISSUE TITLE
Update UI to allow multiple test/module selection

### ISSUE THREAD

**Issue by trentmwillis** [jquery/qunit#953]
As discussed in #951 and #952, it would be beneficial to have a better interface that allows for filtering multiple modules or tests. While this is nice to support those particular features, it would also be beneficial to take this as a chance to address some pain points of working with large test suites. In general, having a dropdown that is thousands of items long is not very useful.

In general, the following features should be considered:

- [x] select individual modules
- [x] select multiple modules
- [ ] select multiple tests
- [x] support grouping of modules (e.g., in Ember tests we have Acceptance, Integration, or Unit tests) [can be accomplished through nested modules]
- [x] filter/search the list of tests/modules

Anything else?

**Comment by mlato-yahoo** [comment]
Based on those requirements I've drafted this simple multi-selector.

![multi-select-mock](https://cloud.githubusercontent.com/assets/15200965/13832492/e6cd9f62-eb99-11e5-8d3c-cae53c3a48d1.png)

Features:
* Multi-select window with checkboxes and scrolling.
* Search box for filtering by module or test name.
* "Submit" button to run selected tests or modules.

Other things that we need to consider:
* How do we tag tests/modules as part of groups? (Acceptance, Integration, etc.)
* Select all/clear all functionality
* Would a module multi-selector replace the module dropdown, and where would it be in the UI?
* **Idea: What about replacing the module select dropdown with a dropdown that opens up into this multi-selector?

Let's make this happen!

**Comment by trentmwillis** [comment]
I think this is a good start.

> How do we tag tests/modules as part of groups? (Acceptance, Integration, etc.)

I have three ideas on how to solve this:

1. Enforce some naming convention (e.g., `<group-name> | <module-name>`)
2. Set a configurable "separator" that then denotes when you're entering a new group (e.g., `QUnit.config.groupSeparator = '|';`). This could make it easier to support nested groups if needed.
3. Introduce metadata into a `module` that would make grouping declarative.

I personally lean towards either 2 or 3.

> Select all/clear all functionality

I believe we could accomplish this similarly to how the current module dropdown works. Reserve the top option as a "clear all" option. This works since selecting all modules is essentially the same as selecting none of the modules.

> Would a module multi-selector replace the module dropdown...

Yes. I think having both would cause too much UI clutter.

> ...and where would it be in the UI?

I like your idea: replace "the module select dropdown with a dropdown that opens up into this multi-selector"

**Comment by gibson042** [comment]
> > How do we tag tests/modules as part of groups? (Acceptance, Integration, etc.)

> I have three ideas on how to solve this:

> 1. Enforce some naming convention (e.g., `<group-name> | <module-name>`)
2. Set a configurable "separator" that then denotes when you're entering a new group (e.g., `QUnit.config.groupSeparator = '|';`). This could make it easier to support nested groups if needed.
3. Introduce metadata into a `module` that would make grouping declarative.

We already have number 3 in the form of [nested modules](https://github.com/jquery/qunit/commit/7be1d6c38cac4370bafdb17b10f0f4dee576bd12) (and also number 1 to some extent; child module names are [prefixed with parent names](https://github.com/jquery/qunit/blob/0f9ae3443a0fc78d96baa2eb86f90b0cba9264b5/src/core.js#L54-L55)). That seems sufficient to me.

> > Would a module multi-selector replace the module dropdown...

> Yes. I think having both would cause too much UI clutter.

> > ...and where would it be in the UI?

> I like your idea: replace "the module select dropdown with a dropdown that opens up into this multi-selector"

Yes, we should be very mindful about top-of-page real estate, too much of which we already consume.

**Comment by mlato-yahoo** [comment]
I've made some progress on the module multi-selector

![multi-select-demo](https://cloud.githubusercontent.com/assets/15200965/14031788/bea08d82-f1cb-11e5-8222-97285144ef3f.png)

Check out the code here:
https://github.com/jquery/qunit/pull/973

Known problems:
* The dropdown doesn't align perfectly when using Firefox.

Possible issues:
* Not tested with IE (I used the IE 7.0 user agent in Safari, but that's not the same).

Optional improvements:
* Clear search field on dropdown close
* Larger dropdown (vertically)
* Shift-click for selecting groups of modules

All feedback and suggestions are welcome, let me know what you guys think!

**Comment by leobalter** [comment]
> Not tested with IE (I used the IE 7.0 user agent in Safari, but that's not the same).

Here is you getting me on my virtual machines to test this :P 

I really want to release the next major version so this (testing on IE6+) won't be a problem anymore.

**Comment by leobalter** [comment]
Does #973 fixes this or should it still be open for selecting multiple tests?

**Comment by trentmwillis** [comment]
I'll review it later today and update this issue.

**Comment by trentmwillis** [comment]
Took a look at #973 and I think it's a great start. I updated the original post to reflect the new features.

The only missing feature that would potentially be beneficial is the ability to select multiple tests from the UI. You can select a single test to re-run and you can select single or multiple modules to run, but there is no way to select multiple tests to run without manually entering them into the URL. However, I imagine this wouldn't be part of the dropdown, probably more like inline checkboxes for each test (think gmail or something similar).

Additionally, the ergonomics of the module dropdown could be improved. I'll open another issue about that tomorrow.

**Comment by sechel** [comment]
Nice work, I tested this for my test suite and experienced an issue that was present with the old dropdown as well: Module names appear multiple times:
![karma](https://cloud.githubusercontent.com/assets/4698832/15826275/3ca8ca76-2c07-11e6-97e5-114c8919dec3.png)
I used to fix this for an earlier version by simple filtering on the `modulesList`, but I thought if you are already working on this you could easily fix this.
It seems to be the result of using a `qunit.module('Learning', function() {` directive multiple times in different modules of the test suite.

**Comment by mlato-yahoo** [comment]
This is an automatically generated message.

mlato@yahoo-inc.com is no longer with Yahoo! Inc.

Your message will not be forwarded.

If you have a sales inquiry, please email yahoosales@yahoo-inc.com and someone will follow up with you shortly.

If you require assistance with a legal matter, please send a message to legal-notices@yahoo-inc.com

Thank you!

**Comment by sechel** [comment]
;-)

**Comment by leobalter** [comment]
I removed the auto-generated comment. It's also a good note to use personal accs on GitHub whenever is possible.

**Comment by trentmwillis** [comment]
Closing this as I don't think the ability to "select multiple tests" is really needed and potential UX solutions would add a good amount of clutter. We can revisit in the future if needed.

**Comment by mlato-yahoo** [comment]
This is an automatically generated message.

mlato@yahoo-inc.com is no longer with Yahoo! Inc.

Your message will not be forwarded.

If you have a sales inquiry, please email yahoosales@yahoo-inc.com and someone will follow up with you shortly.

If you require assistance with a legal matter, please send a message to legal-notices@yahoo-inc.com

Thank you!
