### ISSUE TITLE
Document and prefer multiply-specified URL parameters over comma-separated

### ISSUE THREAD

**Issue by gibson042** [jquery/qunit#954]
Ref gh-951

`QUnit.urlParams` already stores repeated URL parameters in arrays: https://github.com/jquery/qunit/blob/0f9ae3443a0fc78d96baa2eb86f90b0cba9264b5/src/core/utilities.js#L115
For consistency with `QUnit.config` and to preclude ambiguous parsing, we should prefer that method over comma-separated values for specifying composite parameters (e.g., `?moduleId=720ab266&moduleId=0af5a573` instead of `?moduleId=720ab266,0af5a573`), and deprecate the latter anywhere it's already documented.

**Comment by trentmwillis** [comment]
I was unaware of the auto-concatenating of repeated params. I agree we should standardize on a single format. However, I'm not a huge fan of the first approach due to verbosity, but I guess it makes more sense than attempting to figure out if a comma is meant as a separator or if it is just part of the value.

**Comment by leobalter** [comment]
The changes for gh-951 are not released yet, do you want me to revert until we fix it? If we fix it soon we don't need to mind on any breaking change (or reverting commits).

**Comment by gibson042** [comment]
No, I wouldn't revert because e47a7c3db1572387e62846e2e4f39acf7db528f2 just carried forward the already-present pattern of [`testId`](https://github.com/jquery/qunit/commit/e47a7c3db1572387e62846e2e4f39acf7db528f2#diff-217941a76651434529372f12f6de3cbe) (and we don't have any documentation claiming support for comma-separated values, just code).
