### ISSUE TITLE
Confine urlParams references to browser-specific files

### ISSUE THREAD

**Issue by gibson042** [jquery/qunit#955]
`urlParams` is obviously intended for browser utilization, but we have some references to it elsewhere. Most pressing is [test.js:Test#valid](https://github.com/jquery/qunit/blob/e47a7c3db1572387e62846e2e4f39acf7db528f2/src/test.js#L366) (which should be using a `QUnit.config` property), but I'd also like to see [`getUrlParams`](https://github.com/jquery/qunit/blob/e47a7c3db1572387e62846e2e4f39acf7db528f2/src/core/utilities.js#L115-L139) and the other `core` references ([core/config.js](https://github.com/jquery/qunit/blob/e47a7c3db1572387e62846e2e4f39acf7db528f2/src/core/config.js#L71-L104) & [core.js#L1](https://github.com/jquery/qunit/blob/e47a7c3db1572387e62846e2e4f39acf7db528f2/src/core.js#L1)) move into e.g. a "browser reporter" that sets and initializes configuration from `QUnit.urlParams` (which will probably require testing conflict resolution for cases where both inline Javascript and URL parameters try to affect the same `QUnit.config` property).

**Comment by trentmwillis** [comment]
> move into e.g. a "browser reporter" that sets and initializes configuration from QUnit.urlParams

So would it make sense to introduce something like `reporter/url-params.js`? This would keep that functionality confined to the browser and give a clear separation.

> (which will probably require testing conflict resolution for cases where both inline Javascript and URL parameters try to affect the same QUnit.config property)

What should be the resolution here? I tend to think inline JS values would trump the URL params.
