### ISSUE TITLE
Reintroduce QUnit.config.module or QUnit.config.moduleFilter

### ISSUE THREAD

**Issue by gibson042** [jquery/qunit#956]
As noted in https://github.com/jquery/qunit/issues/951#issuecomment-194515024 , both `QUnit.config.module` and `QUnit.config.moduleFilter` were removed by 168b048c682a2c91d66bba8963fd4aad00b8c22e (gh-691) but remain documented as [`moduleFilter`](http://api.qunitjs.com/QUnit.config/). However, it is not appropriate for [deep library code](https://github.com/jquery/qunit/blob/e47a7c3db1572387e62846e2e4f39acf7db528f2/src/test.js#L366) to reach out and inspect URL parameters (cf. gh-955). We should restore one of the `QUnit.config` properties, replace the `QUnit.urlParams` reference, and update the documentation accordingly.

**Comment by trentmwillis** [comment]
As mentioned in the documentation issue, I'm not sure we actually want to reintroduce `module`/`moduleFilter` now that we have `moduleId`. Rather, I think we should remove `module` from the `urlParams` and replace it's functionality with that provided by `moduleId`. However, this would require some reworking of the current UI (mainly updating the dropdown values to be the module ids instead of names).

**Comment by gibson042** [comment]
That would definitely limit the constructibility of QUnit URLs. I _frequently_ do single-module runs for jQuery core (e.g., "https://localhost:8080/test/?module=selector").

**Comment by trentmwillis** [comment]
Is there much advantage to using `?module=selector` instead of `?filter=selector`? I know that the latter has the potential to match other tests, but since you have to specify the exact module name for the former to work, I feel like doing the same for `filter` would yield identical results in many (if not most) cases.

**Comment by gibson042** [comment]
I believe there is. For example, https://github.com/jquery/jquery/blob/master/build/tasks/testswarm.js#L32-L38 uses the parameter to orchestrate continuous integration, which is possible because it accepts values that were defined in the very same codebase and therefore knowable in advance. `filter` is too broad when what's desired is a hard partition along module boundaries.

**Comment by trentmwillis** [comment]
Ah, okay. I think I see the use case better now. In that case, what is the expected behavior from `?module=selector&moduleId=1234567`? Would `module` take precedence? Or will they both be used?

**Comment by Arkni** [comment]
> Ah, okay. I think I see the use case better now. In that case, what is the expected behavior from ?module=selector&moduleId=1234567? Would module take precedence? Or will they both be used?

I think it should run one module if `moduleId` is the same as the hash of `module`, and run the two, otherwise. In other words, the union of the two (+ removing duplicated modules).

**Comment by gibson042** [comment]
[Current behavior](https://github.com/jquery/qunit/blob/e47a7c3db1572387e62846e2e4f39acf7db528f2/src/test.js#L362-L407), which I wouldn't change without careful consideration, is that any test passing _all_ filters (`moduleId`; `testId`; `module`; `filter`) gets to run.

**Comment by trentmwillis** [comment]
Seems legit, let's do it

**Comment by gibson042** [comment]
That still leaves a naming question. The URL parameter is and will likely remain `module`. I believe the `QUnit.config` property should be as well, because AFAICT we never actually released a version in which it was called `moduleFilter` (both the 7409c02813c35b7bd5713fc8650489b0e9049729 rename and the 168b048c682a2c91d66bba8963fd4aad00b8c22e removal debuted in 1.16.0). Any objections?

**Comment by trentmwillis** [comment]
Sounds good to me. It's also consistent with the 1:1 nature of most other params.
