### ISSUE TITLE
Export AMD with name

### ISSUE THREAD

**Issue by fnando** [jquery/qunit#970]
Right now QUnit exports to AMD without specifying a name. When you transpile your code using Babel, and then try to load it with Almond, it fails because no name has been specified. 

I was able to workaround this issue by manually exporting the module as the following:

```js
define("qunit", function() { return QUnit; });
```

Is it possible to change QUnit's definition to explicitly set the exporting name?

**Comment by jzaefferer** [comment]
Can you provide a reduced test case? The description by itself isn't quite enough. The changes in #971 aren't either.

What I'm wondering about: Why are you loading QUnit with Almond, while, as far as I can tell, not using r.js (the optimizer)?

**Comment by jzaefferer** [comment]
Since all the discussion happened in #971, closing this with the same reason.
