### ISSUE TITLE
Stop defining a default QUnit.reset

### ISSUE THREAD

**Issue by gibson042** [jquery/qunit#974]
Since we're deprecating `QUnit.reset`, we should stop [relying on it](https://github.com/jquery/qunit/blob/f13038f8530da11a4c3793f35ffe4d4e1d0531a2/src/test.js#L228-L231). We could replicate the behavior almost perfectly by automatically registering a `testDone` callback that includes the [current logic](https://github.com/jquery/qunit/blob/f13038f8530da11a4c3793f35ffe4d4e1d0531a2/src/test.js#L448-L459), but executes it only when `QUnit.reset === undefined` (or even `!hasOwn.call(QUnit, "reset")`).

I say "almost perfectly" because the current code runs after all `testDone` callbacks, but this proposal would have it run _before_ them. This seems acceptable to me, but if it's a problem we can explore a promise-based remedy.

**Comment by trentmwillis** [comment]
> We could replicate the behavior almost perfectly by automatically registering a `testDone` callback...

I'm assuming we favor this approach since it would take the reporter-centric logic out of core. Otherwise, we could simply keep the function as an internal one. Regardless, instead of using `testDone`, we could register it as a `testStart` / `moduleStart` callback, which  probably increase logic a bit but would give us the results we currently have.

**Comment by gibson042** [comment]
There are a few edge case differences either way (e.g., post-suite DOM state, test duration); the question is whether they matter. I'm of the opinion that they don't, but even so would still prefer your `testStart` approach to my `testDone` suggestion.

**Comment by gibson042** [comment]
This wasn't resolved by 0baf467d56735da6de22c377e991ec799460278a, and was in fact made worse since there's no longer a way to prevent the behavior (which was previously as easy as `QUnit.reset = function(){}`). I'm not in favor of becoming more magical.

**Comment by leobalter** [comment]
My bad I misunderstood this issue.

We can still isolate the operation for QUnit.reset, but should we keep it exposed to the API?

**Comment by gibson042** [comment]
It seems to me that legacy compatibility motivates us to automatically reset the DOM at test boundaries, even though such functionality is arguably more appropriate in a user-defined callback, e.g. `testStart`. But it should always be _possible_ to correct the inverted default and prevent QUnit from doing anything. As of 0baf467d56735da6de22c377e991ec799460278a, the only way to do so is by removing `#qunit-fixture`, which isn't great. And when we consider the weirdness of a DOM coupling in [test.js](https://github.com/jquery/qunit/blob/0baf467d56735da6de22c377e991ec799460278a/src/test.js#L468-L473) that is indirectly dependent upon the HTML reporter (for initial definition of `QUnit.config.fixture`), I think the best approach looks something like the following:
* Initialize `QUnit.config.fixture` in core instead of the HTML reporter, still waiting for a "begin" event but aborting when `hasOwn.call( config, "fixture" )` to avoid overwriting user-provided values (even `undefined` ones).
* Document `QUnit.config.fixture` as a public interface, in particular noting that it can be nulled to disable automatic DOM manipulation.
* Skip DOM resets when `QUnit.config.fixture == null`.
* Throw an exception upon _setting_ of `QUnit.reset`, since we have at least one example of overwriting it and we don't want silent failure to invoke it.

This will preserve the legacy behavior of automatic inter-test DOM resets, but provide a documented means by which to control them, and reduce HTML reporter dependence to boot.

**Comment by trentmwillis** [comment]
@gibson042 this seems like a reasonable approach to me. I can take a crack at implementing it this weekend, if you don't get to it by then.
