### ISSUE TITLE
Next QUnit is 2.0

### ISSUE THREAD

**Issue by leobalter** [jquery/qunit#975]
Hello everyone and specially @jquery/qunit team!

This is the mark to say 2.0 is the next version, except if we need some patch version to fix a bug on QUnit 1.23.0.

That means we need to hold any new features for now and start working removing all the deprecated parts.

The current PRs to merge are only #971 and #919, the others will have to wait, I promise it won't be long.

**Comment by trentmwillis** [comment]
I'll rebase #919 sometime this weekend so we can merge it

**Comment by trentmwillis** [comment]
Also, what about #918? Unless I missed something, seems like we should get those warnings into a release.

**Comment by leobalter** [comment]
I talked to @raphamorim on a private channel and we will meet in person
next week. Applying the warning feature to deprecated api revealed more
complex than planned and that PR became a rabbit hole.

We will still have deprecations after 2.0 pre-3.0 and we may still keep
QUnit.warning as a feature for the good on the future.

**Comment by leobalter** [comment]
A few missing cases at https://github.com/jquery/qunit/milestones/v2.0, but we are close.

**Comment by leobalter** [comment]
2.0.0-rc1 is out! Grab your friends to test it everywhere! 

yay!
