### ISSUE TITLE
Handle QUnit overloading

### ISSUE THREAD

**Issue by leobalter** [jquery/qunit#983]
As reported on twitter by @fnando, QUnit silently fails if it's loaded twice or more in a single suite.

We may investigate how to better handle this, failing or not, it's nice to make it clear.

**Comment by fnando** [comment]
To be more specific, it doesn't failure, but it overrides any define hook on the previous instance silently. The ideal way of dealing with this would either using existing instance or raise an exception saying that only one instance can be defined.

**Comment by trentmwillis** [comment]
> raise an exception saying that only one instance can be defined.

I'm 👍  on this idea. Unless there is a valid use case for having the library defined more than once, I feel it makes the most sense to alert users to the fact they're duplicating dependencies.
