### ISSUE TITLE
Confirm proper async isolation

### ISSUE THREAD

**Issue by gibson042** [jquery/qunit#984]
https://github.com/jquery/qunit/pull/976#discussion_r59634666 suggests that some state may be leaking.

**Comment by platinumazure** [comment]
What sort of state might be leaking? Is this something that needs further investigation, or do we already have a good idea where/why this is happening?

**Comment by gibson042** [comment]
I haven't investigated the why, but the where is in the function returned by `assert.async`—we _should_ be able to pass `test` to `resumeProcessing`, but making that change breaks the test suite. So something is amiss and needs analysis.
