### ISSUE TITLE
Is it possible to do subtest and display pyramid of test

### ISSUE THREAD

**Issue by Thaina** [jquery/qunit#993]
I'm not sure it already possible but if it not I would like to request this feature

Such as I want to do some test with multiple users. But before that I would like to test each user and result each one in each block but still in the same scope of the test. Then do the real test

Ability to display subtest in block and layer each as pyramid could be handy

Something like `assert.test(function(subAssert){ /* subtest */ });` maybe?

**Comment by trentmwillis** [comment]
I'm not sure I understand the use case. What would be the difference between a sub-test and a single test from a module? Why not simply do the same test in a loop with the different member data?

**Comment by Thaina** [comment]
@trentmwillis The difference is variable scope and grouping

It's like a comment in reddit which could be subcomment and subsubcomment. That's the main point. To split it in difference module then it cannot reuse variable I got from the previous test (get userIDs properly is also a test that I do assert)

Another use case is to test many items that could be test each one asynchronously. Ability to asynchronous test each block will be neat. I test 3 user separately and want to display result of test in its own block. But when I do async it was race against each other and report flat result (indently group is better)

**Comment by JamesMGreene** [comment]
You could use nested modules (suites): http://api.qunitjs.com/QUnit.module/

**Comment by Thaina** [comment]
I see, thanks. @JamesMGreene

**Comment by Thaina** [comment]
@JamesMGreene Now I'm still curious. How order the module got called? If it async Promise then how can I specified which one will go in which module. How can I go back into topmost module?

I think `hooks` should have all function of QUnit and instead of `QUnit.test()` we could use `hooks.test()` and get assert to nest module instead

**Comment by trentmwillis** [comment]
@Thaina the modules/tests get called in the order in which they are defined. Tests and hooks (e.g., `beforeEach` / `afterEach`) have built in support for handling async behavior, so long as you return a Promise. See the [API docs here for more info and an example](https://api.qunitjs.com/QUnit.test/).

**Comment by trentmwillis** [comment]
Closing this as the usage of nested modules and Promise handling seems to solve this use case.
